= МАГИЯ

[discrete]
== ОЧКИ МАНЫ

Для сотворения заклинаний нужна энергия, которой обладает каждое живое существо, известная как мана.
Объём маны, в обычных условиях доступный магу для сотворения заклинаний, исчисляется в очках маны (Mana Points, МР).
Чем больше МР у вас есть, тем больше заклинаний вы способны сотворить.
Если у вас не осталось очков маны, вы не можете читать заклинания, пока не восстановите хоть некоторое количество МР.
Маг 1 уровня начинает игру с количеством МР, равным `10 + Магия + 1к6` и получает `Магия + 1к6` с каждым новым уровнем (c 11 только значение Магии).
Сильные маги могут творить заклинания долгое время, не истощая свои запасы маны.
Это говорит о том, что очки маны– ресурс не бесконечный, и умный маг знает, когда тратить ману, а когда лучше поберечь.
Каждое заклинание стоит определённое количество очков маны.
Они тратятся каждый раз, когда совершается действие заклинания, вне зависимости от того, получилось сплести чары или нет.
Магия всегда заставляет платить по счетам.

[discrete]
== ЗАКЛИНАНИЯ И БРОНЯ

Маги могут носить броню, хотя и не обучались этому специально.
Однако доспех затрудняет чтение заклинаний: маг вынужден тратить лишние МР, количество которых зависит от типа брони и её нагрузки.
Эта дополнительная мана тратится на каждое заклинание, так что маг, нацепивший тяжёлую броню, быстро окажется в проигрышном положении.

[caption="Таблица 12. "]
.ЗАКЛИНАНИЯ В БРОНЕ
[cols="~,~"]
|===
|Надета броня |Нагрузка
|Лёгкая кожаная
|1
|Тяжёлая кожаная
|2
|Лёгкая кольчуга
|3
|Тяжёлая кольчуга
|4
|Лёгкая пластинчатая
|5
|Тяжёлая пластинчатая
|6
|===

[discrete]
== ВОССТАНОВЛЕНИЕ ОЧКОВ МАНЫ

Маг восстанавливает очки маны после отдыха.
За каждый полный час отдыха или медитации вы восстанавливаете 1к6 + Магия очков маны.
Если вы будите отдыхать/медитировать полных 8 часов без перерывов, то вы восстанавливаете ману до максимума.

[discrete]
== ЧТЕНИЕ ЗАКЛИНАНИЙ

Вы можете прочитать любое заклинание, сделав успешный бросок и потратив соответствующее количество очков маны.
Бросок заклинания– обычный бросок на Магию.

Обычно учитываются фокусы Магии Созидания, Магии Энтропии, Элементальной Магии и Магии Духа, каждый из которых соответствует одной из магических школ.

====
Бросок заклинания = 3к6 + Магия + фокус (если есть)
====

Если ваш бросок равен или больше сложности (Target Number, TN), вы успешно прочитали заклинание.
Если нет, то заклинание проваливается и не действует никак.
Но МР тратятся в любом случае.

При расчете результата некоторых заклинаний используется Кубик Дракона, так что лучше как-нибудь зафиксируйте выпавшее на нём значение, пока действие заклинания не прекратится.

[discrete]
== СИЛА МАГИИ

Многие заклинания таковы, что беспокоиться нужно только о броске на заклинание.
Если он успешен, то заклинание работает, как ему положено.
Однако иногда, чтобы заклинание произвело какое-то воздействие, вы должны преодолеть природное сопротивление цели.

Сила Магии– это мощь вашего волшебства; некоторые заклинания позволяют цели (или целям) сделать бросок против Силы Магии, чтобы попытаться воспротивиться действию магии или хотя бы отчасти нейтрализовать его.

====
Сила Магии = 10 + Магия + фокус (если есть)
====

И опять повторим: обычно добавляются фокусы Магии Созидания, Магии Энтропии, Магии Элементов и Магии Духа.
Это означает, что если вы специалист по магии энтропии, то вашим энтропическим заклинаниям тяжелее сопротивляться.

Способность, с помощью которой можно сопротивляться магии, зависит от конкретного заклинания.
В описании каждого заклинания будет указано, нужно ли делать бросок и на какую способность, и каковы последствия его успеха или провала.

:leveloffset: +1

'''

include::magic/magic_blood.adoc[]

'''

include::magic/magic_entrop.adoc[]

'''

include::magic/magic_duha.adoc[]

'''

include::magic/magic_prirod.adoc[]

'''

include::magic/magic_sozidan.adoc[]

'''

[format=dsv,separator=;]
|===
Жертва кровью(магия крови);;;
Кровавая рана(магия крови);Кровотечение;Раб крови;
Чтение мыслей(магия крови);;;
Разрушение(магия крови);;;
;;;
Слепота;Ужас;Сон;Ходячий кошмар
Вытягивание жизни;Смертельная магия;Смертельное проклятие;Смертельное облако
Порча уязвимости;Болезненная порча;Отводящая порча;Смертельный сглаз
Слабость;Паралич;Миазма;Массовый паралич
Галлюцинации(талант Магия Энтропии(Подмастерье));;;
Метка медлительности (специлизация Некромантия,талант Магия Энтропии(Подмастерье),;;;
Энтропическое облако(талант Магия Энтропии(Мастер));;;
;;;
Мистический болт;;;
Мистический щит;Теневой щит;;
Вытягивание маны;Поддержка;;
;Очистка маны;Мощь заклинания;Столкновение маны
Взрыв разума;Силовое поле;Поле отталкивания;
;;Телекинетическое оружие;Дробящая темница
;Левитация;;
;Память;;
Щит заклинаний;Магия рассеивания;Анти-магический оберег;Анти-магическая вспышка
Ходячая бомба;Воскрешение мертвого;;
;Смертельный сифон;Заразная ходячая бомба;
Аура мощи (Специлизация мистический воин);;;
Кулак создателя(Специлизация магия силы);Телекинетический взрыв;Притяжение Бездны(Магия Силы);
Духовная метка(Специлизация некромант);;;
Лозоходец(талант Магия Духа (Подмастерье));;;
Наслать сон(талант Магия Духа (Подмастерье));;;
;;;
Стихийный мастер;;;
Поток огня;Огненное оружие;Инферно;
Каменная броня;;;
Шок;Молния;Буря;Цепочка молний
Каменный кулак;Землетрясение;Окаменение;
Хватка зимы;Морозное оружие;Конус холода;Метель
Силки(специлизация Хранитель (Подмастерье));Каменный бросок;;
Эльфийский гнев(специлизация Хранитель );;;
Яма(талант Первобытная магия  (Подмастерье));Каменные объятия;;
Убежище(талант Первобытная магия  );;;
Управление погодой(талант Первобытная магия(Мастер) );;;
Управление ветром(талант Первобытная магия (Послушник) );;;
;;;
Руна нейтрализации;;;
Руна паралича;Руна оберега;Руна отталкивания;
Руна сохранения;;;
Руна запечатывания;;;
Лечение;Восстановление;Массовое восстановление здоровья;
Героическое нападение;Героическая аура;Героическая защита;Спешка
Магический огонек;Масло;Цветение магии;Жалящий рой
Превращение в маленького животного(специлизация Оборотень);;;
Превращение в большого животного(специлизация Оборотень (Подмастерье));;;
Ужасная форма животного(специлизация Оборотень(Мастер) );;;
Регенерация(талант Магия созидания(Мастер));;;
Форма земли(талант  Магия созидания(Подмастерье));;;
Источник(талант Магия созидания(Подмастерье) );;;
Призыв зверя(талант Магия созидания(Подмастерье));;;
Групповое лечение(специлизация Духовный Лекарь);;;
Воскрешение( специлизация Духовный Лекарь(Подмастерье));;;
Оберег жизни( специлизация Духовный Лекарь(Мастер));;;
|===



:leveloffset: -1
