= МАГИЯ

== ОЧКИ МАНЫ (MANA POINTS)

Для сотворения заклинаний нужна энергия, которой обладает каждое живое существо, известная как мана.
Объём маны, в обычных условиях доступный магу для сотворения заклинаний, исчисляется в очках маны (Mana Points, МР).
Чем больше МР у вас есть, тем больше заклинаний вы способны сотворить.
Если у вас не осталось очков маны, вы не можете читать заклинания, пока не восстановите хоть некоторое количество МР.
Маг 1 уровня начинает игру с количеством МР, равным 10 + Магия + 1к6 и получает Магия + 1к6 с каждым новым уровнем (c 11 только значение Магии).
Сильные маги могут творить заклинания долгое время, не истощая свои запасы маны.
Это говорит о том, что очки маны– ресурс не бесконечный, и умный маг знает, когда тратить ману, а когда лучше поберечь.
Каждое заклинание стоит определённое количество очков маны.
Они тратятся каждый раз, когда совершается действие заклинания, вне зависимости от того, получилось сплести чары или нет.
Магия всегда заставляет платить по счетам.

== ЗАКЛИНАНИЯ И БРОНЯ

Маги могут носить броню, хотя и не обучались этому специально.
Однако доспех затрудняет чтение заклинаний: маг вынужден тратить лишние МР, количество которых зависит от типа брони и её нагрузки (см. соответствующую таблицу).
Эта дополнительная мана тратится на каждое заклинание, так что маг, нацепивший тяжёлую броню, быстро окажется в проигрышном положении.

[caption="Таблица 12. "]
.ЗАКЛИНАНИЯ В БРОНЕ
[cols="~,~"]
|===
|Надета броня |Нагрузка
|Лёгкая кожаная
|1
|Тяжёлая кожаная
|2
|Лёгкая кольчуга
|3
|Тяжёлая кольчуга
|4
|Лёгкая пластинчатая
|5
|Тяжёлая пластинчатая
|6
|===

== ВОССТАНОВЛЕНИЕ ОЧКОВ МАНЫ

Маг восстанавливает очки маны после отдыха.
За каждый полный час отдыха или медитации вы восстанавливаете 1к6 + Магия очков маны.
Если вы будите отдыхать/медитировать полных 8 часов без перерывов, то вы восстанавливаете ману до максимума.

== ЧТЕНИЕ ЗАКЛИНАНИЙ

Вы можете прочитать любое заклинание, сделав успешный бросок и потратив соответствующее количество очков маны.
Бросок заклинания– обычный бросок на Магию.

Обычно учитываются фокусы Магии Созидания, Магии Энтропии, Элементальной Магии и Магии Духа, каждый из которых соответствует одной из магических школ.
Чтобы узнать больше о бросках на способности, см.
Главу 6: Игра.

====
Бросок заклинания = 3к6 + Магия + фокус (если есть)
====

Если ваш бросок равен или больше сложности (Target Number, TN), вы успешно прочитали заклинание.
Если нет, то заклинание проваливается и не действует никак.
Но МР тратятся в любом случае.

При расчете результата некоторых заклинаний используется Кубик Дракона, так что лучше как-нибудь зафиксируйте выпавшее на нём значение, пока действие заклинания не прекратится.

== СИЛА МАГИИ (SPELLPOWER)

Многие заклинания таковы, что беспокоиться нужно только о броске на заклинание.
Если он успешен, то заклинание работает, как ему положено.
Однако иногда, чтобы заклинание произвело какое-то воздействие, вы должны преодолеть природное сопротивление цели.

Сила Магии– это мощь вашего волшебства; некоторые заклинания позволяют цели (или целям) сделать бросок против Силы Магии, чтобы попытаться воспротивиться действию магии или хотя бы отчасти нейтрализовать его.

====
Сила Магии = 10 + Магия + фокус (если есть)
====

И опять повторим: обычно добавляются фокусы Магии Созидания, Магии Энтропии, Магии Элементов и Магии Духа.
Это означает, что если вы специалист по магии энтропии, то вашим энтропическим заклинаниям тяжелее сопротивляться.

Способность, с помощью которой можно сопротивляться магии, зависит от конкретного заклинания.
В описании каждого заклинания будет указано, нужно ли делать бросок и на какую способность, и каковы последствия его успеха или провала.


:leveloffset: +1

'''

include::magic/magic_blood.adoc[]

'''

include::magic/magic_entrop.adoc[]

'''

include::magic/magic_duha.adoc[]

'''

include::magic/magic_prirod.adoc[]

'''

include::magic/magic_sozidan.adoc[]

'''

:leveloffset: -1

