= СОЗДАНИЕ ПЕРСОНАЖА
:toc: left
:toclevels: 3

1. ПРОДУМАЙТЕ КОНЦЕПЦИЮ ПЕРСОНАЖА
2. ЗАДАЙТЕ ЗНАЧЕНИЯ СПОСОБНОСТЯМ
3. ВЫБЕРИТЕ ПРЕДЫСТОРИЮ
4. ВЫБЕРИТЕ КЛАСС
5. ЗАКУПИТЕ СНАРЯЖЕНИЕ

:leveloffset: +1
include::person/person_1.adoc[]

include::person/person_2.adoc[]

include::person/person_3.adoc[]

include::person/person_4.adoc[]

include::person/person_5.adoc[]

:leveloffset: -1
== СКОРОСТЬ И ЗАЩИТА (DEFENSE AND SPEED)

И наконец, вам нужно вычислить две величины: Защита и Скорость.
Защита — то, насколько трудно попасть по персонажу во время боя.
Чем она выше, тем лучше.
Вы вычисляете Защиту следующим образом:

====
`Защита = 10 + Ловкость + Бонус щита (если экипирован)`

Бонусы щитов описаны в Главе 4: Оружие и снаряжение.
====

Сейчас вам нужно знать лишь то, что лёгкий щит даёт бонус +1, а средний- +2.
Пример:
Теперь Кейт рассчитывает Защиту своей разбойницы.
Поскольку её Ловкость равна 4, то Защита– 14 (10+4).
Если она возьмёт в руки лёгкий щит, то Защита поднимется до 15.
Скорость– это то, насколько лёгко и быстро ваш персонаж передвигается.
Как правило, за действие движения (move action) ваш персонаж может преодолеть число ярдов, равное его скорости.

Скорость рассчитывается следующим образом:
====
`Скорость Гнома = 8 + Ловкость - штраф доспеха (если экипирован)`
====
====
`Скорость Эльфа = 12 + Ловкость - штраф доспеха (если экипирован)`
====
====
`Скорость Человека = 10 + Ловкость - штраф доспеха (если экипирован)`
====
Большинство доспехов накладывают на Скорость штраф, что отражает их тяжесть и негибкость: всё это замедляет движения персонажа.

