= СПЕЦИАЛИЗАЦИЯ

== КАК ОТКРЫТЬ СПЕЦИАЛИЗАЦИЮ

Считается, что любая специализация по умолчанию становится доступной, когда вы достигаете 6 уровня.
Это предоставляет вам большой выбор.
Однако ДМ может потребовать, чтобы вы ещё потрудились, чтобы получить желаемую специализацию.
Иначе говоря, открыть специализацию можно тремя способами:

* Найти учителя.
Это НИП, который уже обладает данной специализацией.
У НИПа должны быть свои причины помочь вам – они могут потребовать денег, услуг, присяги или чего-то подобного за то, чтобы обучить вас.
* Вы можете выполнить квест.
Квест может быть практически любым, но обычно ваш ДМ создаёт отдельное приключение, по завершении которого вы открываете вожделенную специализацию.
Например, если вы желаете стать Духовным Целителем, то должны найти доброго духа в Тени, готового вам помочь.
* Вы можете найти учебник.
Сведения о некоторых специализациях содержатся в книгах, прочитав которые можно обучиться.
Например, есть множество запрещённых книг по магии крови, и многих магов они толкнули на тёмный путь.

== Специализации мага

[discrete]
=== Мистический Воитель

Класс ;; Маг.
Требование ;; Магия 3 или больше, Ловкость 3 или больше.

Вы овладели могущественным умением сочетать искусство магии и ближнего боя.

Ученик ;; Вы овладеваете новым типом оружия на ваш выбор, используя для удовлетворения требований к Силе способность Магии.
Вы также можете перейти в режим Боевой Магии совершив действие активации.
В этом режиме вы прибавляете Магию, а не Силу к урону от атак ближнего боя.
Но при этом каждое заклинание стоит на 2 очка маны больше.
Режим Боевой Магии можно отключить другим действием активации.
Подмастерье ;; Нагрузка брони снижается на 3.
Мастер ;; Когда вы активируете Боевую Магию, вы можете потратить 5 МР на то, чтобы принять обличие, частично принадлежащее материальному миру, частично– Тени.
Эти чары называются Теневым Саваном и делает тело мага призрачным и двоящимся.
Теневой Саван повышает вашу защиту на 3, но каждый раунд вы должны тратить 3 очка маны (в начале вашего хода), чтобы поддержать действие заклинания.
В противном случае действие Савана мгновенно прекращается, но режим Боевой Магии остаётся активным.

'''

[discrete]
=== Маг Крови

Класс ;; Маг
Требования ;; Телосложение и Магия 3 или выше

Вы познали запретное искусство Магии Крови.

Ученик ;; Вы можете использовать собственную кровь для усиления своих заклинаний.
Для этого вам сначала нужно использовать действие активации, чтобы перейти в режим Мага Крови.
Когда, находясь в этом режиме, вы читаете заклинание, вы можете причинить себе 1к6 проникающего урона, чтобы получить количество очков маны, эквивалентное полученному урону.
Эти очки маны должны быть использованы на заклинание в этом же раунде, или будут потеряны.
Хотя вы можете использовать полученную таким образом ману на заклинания любой школы, заклинания Крови вы можете использовать только в режиме Мага Крови.
Пока вы находитесь в этом режиме, вы не можете быть исцелены зельям или заклинаниями Духа.
Вы можете выйти из режима Мага Крови, вновь использовав действие активации.
Подмастерье ;; Вы можете использовать кровь союзника, отданную по желанию, чтобы усилить свои заклинания.
Этот приём работает также, как и на уровне ученика, однако урон получаем ваш союзник.
Он должен находиться не далее 6 ярдов от вас во время чтения заклинания.
Мастер ;; Теперь вы можете использовать кровь любого человека для усиления своих заклинаний.
Совершив малое действие, вы можете попытаться вытянуть крови цели, находящейся находится не далее 6 ярдов от вас.
Для этого необходим встречный бросок на Магию (Кровь) против Воли (Вера или Самоконтроль) цели.
В случае выигрыша талант работает так же, как и на уровне ученика.
Если цель, из которой вы тянете кровь, соседствует с вами и беспомощна (без сознания, связана и т.п.), вы причиняете ей 2к6 проникающего урона (одновременно понимая, почему маги Империи Тевинтер не пользуются популярностью среди простого народа)

'''

[discrete]
=== Духовный Целитель

Класс ;; Маг
Требование ;; Общение и Магия 3 или выше

Вы можете призывать дружелюбных духов для лечения людей.

Ученик ;; Вы научились вызывать духов.
Вы знаете заклинания, относящиеся к типу Целительных.
Чтобы использовать заклинания этой группы, вы должны войти в Режим Призыва.
Это требует действия активации и успешного броска на Магию (Дух) против сложности 14. Если вы проваливаетесь, и на всех трёх кубиках выпадают одинаковые числа, вы должны сделать бросок по таблице Магических Провалов.
В случае удачного броска вы сумели призвать подходящего духа, и можете читать заклинания духовного целителя, пока находитесь в этом режиме.
Из режима вы можете выйти другим действием активации, отпустив духа туда, откуда он прибыл.
Подмастерье ;; Вы выучиваете заклинание духовного целителя Воскрешение.
Мастер ;; Вы выучиваете заклинание духовного целителя Хранитель Жизни.

'''

[discrete]
=== Маг Силы

Класс ;; Маг
Требования ;; Магия и Воля 3 или выше.

Вы знаете, как управлять чистой силой магии.

Ученик ;; Вы выучиваете заклинание Мага Силы кулак создателя.
Подмастерье ;; Вы выучиваете заклинание Мага Силы телекинетический взрыв.
Мастер ;; Ваше мастерство как мага делает вас непоколебимым.
Когда противник использует против вас приёмы рывок или сбить с ног, вы можете воспротивиться его эффектам, потратив ману (1 очко в случае рывка и 2 очка в случае сбить с ног).

'''

[discrete]
=== Хранитель

Класс ;; Маг
Требования ;; Разум и Магия 3 или выше, принадлежность к долийцам.

Вы познали древние тайны эльфийской магии.

Ученик ;; Вы выучиваете заклинание Хранителя гнев эльфов.
Подмастерье ;; Вы узнаёте заклинание Хранителя ловушка.
Мастер ;; Вы черпаете силу из извечного круговорота смерти и возрождения в природе.
Когда вы убиваете противника гневом эльфов, вы восстанавливаете 1к6 здоровья, если ранены.
Если у вас и так полное Здоровье, никакой выгоды вы не получаете.

'''

[discrete]
=== Оборотень

Класс ;; Маг.
Требования ;; Телосложение и Магия 3 или выше.

Вы можете принимать облик других животных.

Ученик ;; Вы выучиваете заклинание оборотня облик маленького животного.
Когда вы принимаете с помощью этого заклинания форму зверя, используете следующие правила.
Вы не можете говорить или колдовать, будучи в облике животного.
Заклинания, которые вы сотворили до превращения, работают, как работали до этого, и вы можете тратить ману, чтобы поддержать их.
Ваши Разум и Магия и Здоровье сохраняют прежнее значение, однако остальные характеристики зависят от того, какое заклинание Оборотня вы использовали.
Подмастерье ;; Вы выучиваете заклинание оборотня облик большого животного.
Мастер ;; Вы выучиваете заклинание оборотня облик ужасной твари.

'''

== Специализации разбойника

[discrete]
=== Асассин

Класс ;; Разбойник
Требование ;; Разум 3 или выше, Ловкость 3 или выше.

Вы знаете, как убивать быстро и эффективно.

Ученик ;; Вы можете изучить ближайшую цель, чтобы обнаружить уязвимые места и использовать это знание в последующей битве.
Совершив действие активации, вы можете наложить на одну цель в поле вашего зрения, находящуюся не далее 10 ярдов от вас, Метку Смерти (Marked for Death).
Все атаки дальнего и ближнего боя по тому, что помечен, получают бонус +1 к урону.
Метка существует до конца сцены (или, что чаще– до конца цели).
На героя не может быть наложено более одной Метки Смерти за одну сцену.
Подмастерье ;; Ваши атаки неожиданны, точны и смертоносны.
Когда вы используете умение разбойника грязная драка, сложность броска вашего противника на Телосложение (Выносливость) равна 15, а не 11, как обычно.
В добавление к этому один раз за сцену вы можете использовать грязную драку, тратя на это свободное действие.
Мастер ;; Вы умеете использовать слабости своего противника.
Когда вы наносите удар в спину противнику, на котором лежит Метка Смерти, то причиняете дополнительные 1к6 урона.

'''

[discrete]
=== Бард

Класс ;; Разбойник
Требование ;; Общение и Ловкость 3 или выше.

Вы знаете песни, которые поднимают боевой дух.
На то, чтобы начать петь песню, тратится основное действие.
На её поддержку каждый раунд необходимо тратить дополнительное действие.

Ученик ;; Вы умеете петь Песнь Отваги.
Союзники в радиусе 12 ярдов от вас получают бонус +1 к броскам атаки, пока песня звучит.
Подмастерье ;; Вы умеете петь Песнь Дружбы.
Она, также как и остальные песни, может использоваться во время боёв, однако гораздо больше она подходит для сцен отыгрыша.
Вы поёте песню, которая приносит в компанию дух гармонии и товарищества.
До конца сцены отыгрыша (или– в случае боевой сцены– пока песня поддерживается) герои получают бонус +1 к броскам на Общение (Этикет, Расследование, Убеждение и Соблазнение).
Мастер ;; Вы умеете петь Песнь Очарования.
Когда вы используете эту песню, вы можете один раз в раунд очаровать одного противника, находящегося не далее 16 ярдов от вас.
Для этого необходим встречный бросок на Общение (Выступление) против Воли (Самоконтроль) цели.
Если вы выиграли, то цель лишается права действовать на следующем ходу

'''

[discrete]
=== Дуэлянт

Класс ;; Разбойник
Требование ;; Ловкость и Восприятие 3 или выше и Бой с оружием в обеих руках (Ученик) или выше.

Вы мастер точных и быстрых ударов.

Ученик ;; Вы овладеваете оружием типа Дуэльное.
Когда вы используете стиль Боя с оружием в обеих руках и используете также мэн-гош или шипастый щит в неосновной руке, вы получаете бонус +1 к броскам атаки и +1 к Защите в ближнем бою.
Обычно те, кто использует этот стиль боя, умеют владеть либо первым, либо вторым.
Подмастерье ;; Ваши удары приходятся в самые уязвимые места.
Используя Бой с оружием в обеих руках, вы получаете +1 к наносимому в ближнем бою урону.
Мастер ;; Ваш намётанный глаз способен заметить брешь в броне противника.
Применяя приём Пробивания Брони, вы наносите проникающий урон.
В обычных условиях этот приём уменьшает класс брони вдвое, но проникающий урон позволяет игнорировать броню вообще.

'''

[discrete]
=== Снайпер

Класс ;; Разбойник.
Требования ;; Ловкость и Восприятие 3 или выше и либо Лучник (Подмастерье), либо Стиль Боя с Метательным Оружием (Подмастерье).

Вы великолепный стрелок.

Ученик ;; Ваши атаки в дальнем бою столь сильны, что могут оттолкнуть ваших противников назад и сбить их с ног.
Вы можете использовать приём опрокинуть за 1 SP вместо обычных 2. Одновременно вы можете оттолкнуть цель на 2 ярда назад до того, как опрокинете её (эффект аналогичный рывку, однако более ограниченный).
Подмастерье ;; Вы можете обрушить на ваших противников ливень стрел.
Вы можете использовать приём град стрел за 5 SP.
Это позволяет вам сделать две дополнительные дальнобойные атаки против той же цели либо другой в радиусе 10 ярдов от вас, находящейся в поле вашего зрения.
Для того, чтобы сделать эти две атаки, вы должны зарядить оружие; таким образом, вы должны использовать приём быстрой перезарядки дважды или больше, и только потом на град стрел.
Если у вас при броске на эту атаку выпадают дубли, вы не получаете SP.
Мастер ;; Вы находите слабое место в защите своего противника.
Когда вы во время дальнобойной атаки используете приём пробить броню, вы наносите проникающий урон (обычно этот приём снижает Класс Брони цели вдвое, в то время как проникающий позволяет игнорировать его вообще).

'''

[discrete]
=== Следопыт

Класс ;; Разбойник.
Требования ;; Общение и Восприятие 3 или выше, и фокус Общения (Обращение с животными).

Ваши знания дают вам немалое преимущество, когда вы находитесь на лоне природы.

Ученик ;; Вы можете приманивать животных, которые находятся неподалёку, и побуждать их сражаться на вашей стороне.
Вначале вы делаете бросок на Общение (Обращение с животными); это действие занимает 2к6 минут.
Базовая сложность равна 13, но ДМ может изменить её, исходя из особенностей места, которые вы избрали, и агрессивности животных.
Каждый ранг успеха уменьшает время броска на 1 минуту.
Если бросок успешный, вы приманиваете животное и контролируете его во время следующего боя.
Когда бой закончен или прошло полчаса, животное уходит.
С рангом ученика в этом таланте вы можете приманивать обычных животных вроде собак, волков или хищных птиц (можете использовать характеристики сокола).
При наличии разногласий насчёт того, каких животных вы приманили с помощью этого таланта, последнее слово остаётся за ДМом.
Подмастерье ;; Время, проведённое в дикой местности, помогло вам отточить умение нападать неожиданно.
Когда вы атакуете противника и застаёте его врасплох, вы получаете бонус +2 к урону.
Мастер ;; Вы можете приманивать больших животных, таких, как чёрные медведи, бронто, галла, и даже гигантские пауки.
Базовая сложность броска на Общение (Обращение с животными) по-прежнему равна 13, хотя животные такого размера отличаются свирепым нравом.

'''

[discrete]
=== Тень

Класс ;; Разбойник.
Требования ;; Ловкость 4 или выше и следующие фокусы Ловкости: Ловкость рук и Скрытность.

Вы обитаете в тенях.

Ученик ;; Вы — мастер скрытности.
Использовав действие активации, вы можете перейти в режим Тени и получить следующие преимущества.
Вы получаете бонус +1 к броскам на Ловкость (Скрытность) и Ловкость (Ловкость Рук).
Вашим противникам трудно нанести вам эффективный удар.
Они получают штраф -1 ко всем броскам урона против вас.
Вы можете выйти из режима тени, использовав свободное действие.
Подмастерье ;; Вы можете запутать своего противника и заставить его промахнуться, атаковав иллюзорного врага.
Будучи в режиме Тени, вы можете использовать приём приманка за 2 SP.
Сделайте бросок на Ловкость (Скрытность) и зафиксируйте результат.
До следующего хода каждый, кто атакует вас в ближнем или дальнем бою, должен сделать бросок на Восприятие (Зоркость) против сложности, равной величине вашего предыдущего броска.
Тот, кто его провалил, делает атаку и тратит действие, но промахивается.
Мастер ;; Вы выбираете идеальный момент для атаки.
Когда вы наносите противнику удар в спину, будучи в режиме тени, добавьте Разум к вашему урону.

'''

== Специализации воина

[discrete]
=== Берсерк

Класс ;; Воин
Требование ;; Сила и Воля 3 или выше

Ярость становится вашим оружием.

Ученик ;; Вы умеете приходить в состояние боевой ярости.
Вы можете, использовав действие активации, включить режим Берсерка.
Вы получаете бонус +2 к броскам на Волю (Отвага) и Волю (Мораль), пока находитесь в этом режиме.
Вы также получаете бонус +1 ко всем броскам на урон в ближнем бою.
Однако одновременно вы получаете штраф -2 к Защите и -1 к броскам на Восприятие, пока находитесь в режиме Берсерка.
Выйти из режима вы можете как сами, снова использовав действие активации, так и просто подождать до конца боевой сцены, когда это состояние пройдёт само собой.
Подмастерье ;; Ваша ярость становится сильнее.
Будучи в режиме Берсерка, вы получаете те же штрафы и бонусы, что и ученик, за исключением бонуса к урону в ближнем бою, который повышается до +3.
Мастер ;; В ярости вы просто неудержимы!
Вы можете использовать приём Смертоносного Удара (Lethal Blow) за 4 SP, а не за 5, как обычно, когда находитесь в режиме Берсерка.

'''

[discrete]
=== Витязь

Класс ;; Воин
Требования ;; Общение и Сила 3 или выше.

На поле боя вы — воплощение Силы, ведущее войска за собой.

Ученик ;; Ваш боевой клич наводит ужас на противников.
Когда вы используете стремительную атаку, вы можете издать боевой клич, в результате чего все враги в радиусе 8 ярдов получают -1 к атаке на их последующий ход.
Подмастерье ;; Вы ведёте союзников в бой, наполняя их сердца вдохновением.
Сначала вы должны использовать действие активации, чтобы перейти в режим Сплочения.
Ваши союзники в радиусе 8 ярдов получают +1 к Защите на время активности этого режима.
Отключается режим другим действием активации.
Мастер ;; Ваше присутствие на поле боя невозможно игнорировать.
Если вы находитесь в режиме Сплочения, указанный выше бонус распространяется на союзников в радиусе 12 ярдов.
Также они получают бонус +1 к броскам на Волю (Отвагу) и Волю (Мораль).

'''

[discrete]
=== Храмовик

Класс ;; Воин
Требование ;; Магия и Сила 3 или выше.

Церковь обучила вас справляться с магами.

Ученик ;; Вы обучены ментальным техникам, которые помогают противостоять магии.
Вы получаете бонус +2 к броскам на сопротивления заклинаниям и другим формам магии.
Подмастерье ;; Ваши удары высасывают ману противника.
Когда вы наносите в ближнем бою удар магу (или другому существу, использующему ману), он теряет 1к6 + ваша Магия очков маны в дополнение к обычному урону.
Мастер ;; Вы можете очистить окружающую территорию от действующей магии.
На это требуется большое действие и предельная концентрация, в результате чего персонаж получает -2 к Защите до своего следующего хода.
Все действующие заклинания в радиусе 6 ярдов от вас немедленно развеиваются.

'''

[discrete]
=== Шевалье

Класс ;; Воин.
Требования ;; Сила и Ловкость 3 или выше и Стиль Боя Верхом (Подмастерье).

Вы принадлежите к элите Орлея.

Ученик ;; Вы владеете оружием типа Пики.
Вы также умеете выводить противника из себя меткими оскорблениями.
Вы тратите на приём раздразнивания 1 SP вместо обычных 2. Делая бросок на этот приём, вы можете использовать Общение (Этикет) вместо Общения (Запугивание).
Это отражает умение орлесианцев оскорблять, оставаясь вежливыми.
Подмастерье ;; Ваши удары пикой по силе соперничают с ударами голема.
Когда вы, будучи верхом, делаете стремительную атаку, вы можете добавить 1к6 урона, если дерётесь оружием типа Пики.
Если же у вас в руках какое-то другое оружие ближнего боя, то вы получаете бонус +1 к нанесённому урону.
Мастер ;; Вы извлекаете максимум выгоды из того, что находитесь верхом.
Когда вы на коне, вы можете использовать бег как дополнительное действие, получая при этом бонус +1 к Защите.

'''

[discrete]
=== Защитник

Класс ;; Воин Требования ;; Телосложение и Ловкость 3 или выше и Стиль Боя с Оружием и Щитом (Подмастерье).

Вы знаете, как защищать окружающих.

Ученик ;; Вы можете защищать союзника, используя своё тело и щит.
Выберите союзника и перейдите в режим Защитника (Guardian mode), использовав действие активации.
Когда этот союзник соседствует с вами, он получает +2 к Классу Брони.
Однако каждый раз, когда ваш союзник получает урон, вы тоже получает 2 проникающего урона.
Вы можете изменить цель защиты, использовав свободное действие.
Также вы можете, тоже ценой свободного действия, выйти из режима Защитника.
Подмастерье ;; Если вы твёрдо стоите на земле, никому не под силу сдвинуть вас.
Когда вы находитесь в режиме Защитника, приёмы рывок и сбить с ног не действуют на вас.
Мастер ;; Те, кто ударил вашего "подзащитного", тотчас же сталкиваются с последствиями.
Если вы в режиме Защитника и противник нанёс успешный удар вашему союзнику, вы можете, использовав свободное действие, сразу же атаковать этого противника (при необходимости передвинувшись на 2 ярда или меньше, чтобы соседствовать с ним).
При выпадении дублей на броске этой атаки вы получаете SP, как обычно.
Вы можете сделать это только один раз за раунд.
После атаки все снова действуют в порядке обычной инициативы.
Подобное действие не считается вашим ходом и, соответственно, не уменьшает количество действий, доступных вам за ход.

'''

[discrete]
=== Воин Духа

Класс ;; Воин.
Требования ;; Магия и Воля 3 или выше.

Вы можете использовать силу Тени.

Ученик ;; Вы можете окутать себя мистической энергией.
Использовав действие активации, вы переходите в режим Воина Духа.
Это даёт вам бонусы +1 к Защите и +1 к броскам на Магию при сопротивлении заклинаниям и другим магическим атакам.
Вы можете выйти из режима Воина Духа, использовав свободное действие.
Подмастерье ;; Вы можете заряжать ваше оружие энергией Тени.
В режиме Воина Духа ваши атаки ближнего и дальнего боя считаются магическими.
Это позволяет вам наносить полный урон Бестелесным существами вроде теней.
Это также даёт вам бонус к урону, равный вашей Воле, когда вы атакуете демонов и других существ Тени.
Мастер ;; Вы можете наполнить своё тело энергией Тени и затем резко выплеснуть её.
Находясь в режиме Воина Духа, вы можете использовать приём взрыв Тени за 4 SP.
Волна сияющей энергии причиняет 1к6 проникающего урона всем противникам, которые находятся в радиусе четырёх ярдов от вас.
Демоны и другие существа Тени вместо этого получают 1к6 + Воля проникающего урона.

'''
