= ТАЛАНТЫ

Есть вещи, к которым у вашего героя природные склонности— или же он специально учился их делать; и то и другое зовётся талантами.
Они— одно из средств, наряду с классом и предысторией, которое позволяет изменить персонажа на свой манер.
Выбор таланта— важный компонент создания персонажа.
Любой талант имеет два ранга: ученик (novice) и подмастерье (journeyman), каждый из которых даёт свои игровые преимущества.
Прежде чем получить ранг подмастерья какого- либо таланта, вам необходимо сначала стать в нём новичком.

Новые таланты и ранги в них вы получаете в зависимости от вашего класса.
Как правило, вы получаете новый ранг таланта на нечётном уровне (1, 3, 5 и т.д.).
Также класс определяет набор талантов, которые вам доступны.
Вы не можете взять талант, к которому не имеете доступа из-за класса.
Большинство талантов также имеют определённые требования, например, наличие фокуса на каком-то типе оружия.
Если ваш персонаж не соответствует требованиям, то вы не можете взять талант.
В лист персонажа таланты записываются так: сначала— название таланта, потом, в скобках, ранг развития.
Например, Командир (Подмастерье) или Музыка (Ученик).

[discrete]
==== ДРЕССИРОВКА

Классы ;; Маг, Разбойник и Воин.
Требования ;; Нет.

Вы знаете, как дрессировать животных.

Ученик ;; Вы знаете основы того, как надо управляться с животными.
За неделю дрессировки вы можете обучить животное слушаться простых команд вроде "К ноге", "За мной", или "Фас".
Число команд, которому вы можете обучить ваше животное, равно вашему Общению.
Подмастерье ;; Вы можете обучить животное командам посложнее, вроде "Охраняй это место" или "Если увидишь незнакомцев, беги ко мне".
Обучение такой команде занимает две недели, и число команд, которые может выполнять животное, повышается до вашего Общения + 2.

'''

[discrete]
==== ОПЫТ НОШЕНИЯ БРОНИ

Класс ;; Воин.
Требования ;; Нет.

Вы обучены сражаться в броне.
Вы получаете только штраф к Скорости, тогда как те, кто таким талантом не обладают, получают штраф к Ловкости (и, таким образом, к Скорости— которая зависит от величины Ловкости— тоже).

Ученик ;; Вы можете носить кожаную броню и кольчуги (mail armor), не получая штрафа к Ловкости.
Подмастерье ;; Вы можете носить пластинчатые доспехи (plate armor) , не получая штрафа к Ловкости.

'''

[discrete]
==== ЛУЧНИК

Классы ;; Разбойник и Воин.
Требования ;; Владение оружием типа Лук.

Вы умело обращаетесь с луками и арбалетами.

Ученик ;; Вы умеете правильно целиться.
Когда вы совершаете действие прицеливания (take aim action) из лука или арбалета, вы получаете бонус +2 к броску атаки вместо обычного +1.
Подмастерье ;; После долгих тренировок вы научились перезаряжать оружие быстрее, чем обычный лучник.
На перезарядку лука теперь уходит свободное действие (free action), а арбалета— дополнительное действие (minor action).

'''

[discrete]
==== ХИРУРГИЯ

Классы ;; Маг, Разбойник и воин.
Требования ;; Фокус Разума (Лечение).

Вы умеете обрабатывать раны и лечить болезни.

Ученик ;; Вы овладели хирургическим искусством, и оказываете помощь уверенной рукой.
Теперь вы тратите на Лечение дополнительное действие.
Подмастерье ;; У вас умелые руки целителя.
Когда вы совершаете действие лечения, ваш союзник восстанавливает количество Здоровья, равное удвоенному Кубик Дракона + Разум.

'''

[discrete]
==== КОМАНДИР

Классы ;; Маг и Воин.
Требования ;; Общение 2 или выше.

Вы прирождённый лидер.

Ученик ;; Одно ваше присутствие вдохновляет союзников.
Если вы потратите большее действие на то, чтобы совершить какой-нибудь пафосный жест (воздеть над головой меч, издать боевой клич, взмахнуть знаменем и пр.), ваши союзники получают бонус +1 к броскам на Волю (Отвага) до конца боя.
Подмастерье ;; Союзники повинуются вашим командам.
Любой НИП под вашим командованием получает бонус +1 к броскам на инициативу.

'''

[discrete]
==== ЗНАКОМСТВА

Классы ;; Маг, Разбойник и Воин.
Требования ;; Общение 1 или выше.

У вас много знакомств, подчас в самых неожиданных местах.

Ученик ;; Вы можете попытаться установить контакт с НИПом с помощью броска на Общение (Убеждение).
ДМ устанавливает TN (уровень сложности) в зависимости от того, насколько велика вероятность, что НИП знает вашего героя или они имеют общих друзей.
Чем дальше обитает НИП от места, где родился герой, или выше/ниже его по положению в обществе, тем больше будет УС. Собеседник будет настроен дружелюбно, но помогать вам без какой-либо веской причины не станет.
Вы не можете установить подобный контакт с НИП, который уже настроен по отношению к вам недружелюбно или считает вас врагом.
Подмастерье ;; После того, как первый контакт установлен, вы можете попытаться попросить об услуге, для чего нужно сделать другой бросок на Общение (Убеждение).
УС зависит от характера услуги и неприятностей, которые она может принести собеседнику.

'''

[discrete]
==== МАГИЯ СОЗИДАНИЯ

Класс:: Маг
Требования ;; Фокус Магии (Созидание).

Вы познали тайны Магии Созидания.

Ученик ;; Вы можете вызвать блуждающий огонёк (light wisp), не тратя на это ману.
Огонёк висит над вашим плечом, пока вы не развеете его, и освещает 10 ярдов пространства вокруг вас с яркостью фонаря.
Вызов или развеивание огонька— свободные действия.
Подмастерье ;; Вы глубоко постигли принципы Магии Созидания.
Когда вы творите заклинание Созидания, оно стоит на 1 очко маны меньше, чем обычно, до минимума 1 очко.
Вы также получаете новое заклинание Созидания.
Мастер ;; Магия Созидания пропитывает вашу плоть, давая бонус +1 к Защите.
Вы также получаете новое заклинание Созидания.

'''

[discrete]
==== СТИЛЬ БОЯ С ДВУМЯ ОРУЖИЯМИ

Классы ;; Разбойник и Воин.
Требования ;; Ловкость 2 или выше.

Вы можете сражаться, держа одно оружие в основной руке, а второе— в неосновной.
Вы не можете использовать для этого двуручное оружие.

Ученик ;; Бой двумя оружиями может дать вам преимущество как в атаке, так и в защите.
Если вы совершаете действие активации (active action), вы получаете либо +1 к броску атаки ближнего боя, либо +1 к Защите от атак в ближнем бою до конца боя.
Изменить бонус с нападения на защиту и наоборот вы можете, вновь предприняв действие активации.
Подмастерье ;; Ваши выпады столь быстры, что клики для стороннего наблюдателя сливаются в расплывчатые полосы.
Приём Молниеносной Атаки (Lightning Attack) стоит 2 SP, а не 3, как обычно, если вы применяете его, сражаясь с оружием в обеих руках.

'''

[discrete]
==== МАГИЯ ЭНТРОПИИ

Классы ;; Маг.
Требования ;; Фокус Магии (Энтропия)

Вы познали тайны магии Энтропии.

Ученик ;; Вы получаете способность видеть смерть.
Когда у кого-то в поле вашего зрения здоровье падает до 0, вы можете сказать, через сколько раундов он умрёт.
Подмастерье ;; Вы глубоко постигли принципы Магии Энтропии.
Когда вы творите заклинание Энтропии, оно стоит на 1 очко маны меньше, чем обычно, до минимума 1 очко.
Вы также получаете новое заклинание Энтропии.

'''

[discrete]
==== ВЕРХОВАЯ ЕЗДА

Классы ;; Маг, Разбойник и Воин.
Требования ;; Фокус Ловкости (Верховая езда).

Вы— искусный наездник и неплохо управляетесь с лошадьми и другими ездовыми животными.

Ученик ;; Вы умеете быстро садиться на коня.
Вы можете вскочить в седло, использовав на это свободное действие.
Подмастерье ;; Скакун, которым вы управляете, несётся быстрее ветра.
Будучи верхом, вы получаете +2 к Скорости.

'''

[discrete]
==== ЛИНГВИСТИКА

Классы ;; Маг, Разбойник и Воин.
Требования ;; Нет.

Вы легко овладеваете новыми языками, в том числе и теми, на которых говорят далеко за границами Ферелдена.
Когда вы выучиваете новый язык, вы сразу приобретаете способность и разговаривать, и писать на нём— однако есть два исключения.
На Древнем Тевине (Ancient Tevene) можно только читать, поскольку это мёртвый язык.
На Эльфийском можно лишь говорить, поскольку письменность известна лишь Хранителям, которые держат её в тайне.

Ученик ;; Вы выучиваете дополнительный язык из следующего списка: Древний Тевин (Ancient Tevene), Андер (Ander), Антиванский (Antivan), Гномий (Dwarven), Эльфийский (Elven), Орлейский (Orlesian), Кунлат (Qunlat), Ривайни (Rivaini), Торговый язык (Trade Tongue).
Подмастерье ;; Вы выучиваете новый язык из списка выше.
Вы также можете попытаться сымитировать специфический диалект с помощью броска на Общение (Исполнение).

'''

[discrete]
==== НАУКА

Классы ;; Маг, Разбойник и Воин.
Требования ;; Разум 2 или выше.

Вас отличает пытливый ум и отличная память.

Ученик ;; Вы учились с усердием.
Если вы делаете успешный бросок какой-нибудь из научных фокусов Разума, ДМ даёт вам дополнительную информацию по этой теме.
К научным фокусам относятся все, в названии которых есть слово «Знание»: Знание Культуры, Знание Истории и т.п. Какую именно дополнительную информацию получит персонаж, и насколько она пригодится для решения насущного вопроса, решает ДМ.
Подмастерье ;; Вы— исследователь со стажем.
Когда вы делаете бросок на Разум (Научные Исследования), являющийся частью расширенного броска (advanced test), вы получаете +1 к результату каждого Кубика Дракона.
Это позволяет быстрее достичь нужного результата.
Про расширенные броски рассказано в Книге Мастера; если хотите узнать подробнее, спрашивайте своего ДМа.

'''

[discrete]
==== МУЗЫКА

Классы ;; Маг, Разбойник и Воин.
Требования ;; Фокус Общения (Выступление) или Разума (Знание Музыки).

Вы от природы музыкальны.

Ученик ;; Вы умеете играть на инструменте, петь, писать музыку и читать ноты.
Подмастерье ;; Вы продолжаете совершенствовать себя как музыканта: вы научились играть на других инструментах.
Количество инструментов, на которых вы можете играть, равно вашему Общению.

'''

[discrete]
==== МАГИЯ ЭЛЕМЕНТОВ

Классы ;; Маг.
Требование:: Фокус Магии (Элементы).

Вы познали тайны магии Элементов.

Ученик ;; Вы можете создать у себя в руках небольшой сгусток пламени, не тратя на это ману.
Это пламя нельзя использовать в бою, однако им можно поджечь что-нибудь.
Пламя остаётся у вас в руке, пока не будет рассеяно.
Создание и рассеивание пламени— свободные действия.
Подмастерье ;; Вы глубоко постигли принципы Магии Элементов.
Когда вы творите заклинание Элементов, оно стоит на 1 очко маны меньше, чем обычно, до минимум 1 очка.
Вы также получаете новое заклинание Элементов.

'''

[discrete]
==== МОЛНИЕНОСНЫЕ РЕФЛЕКСЫ

Классы ;; Маг, Разбойник, и Воин.
Требование:: Ловкость 2 или выше.

Вы реагируете на опасность молниеносно, на уровне инстинктов.

Ученик ;; Вы можете приготовиться к последующему действию мгновенно.
Готовность для вас – свободное действие.
Подмастерье ;; Вы молниеносно вскакиваете на ноги, равно как и падаете плашмя.
Вам нужно свободное действие на то, чтобы встать на ноги или лечь на землю.
В обычных обстоятельствах на это надо тратить часть действия движения.

'''

[discrete]
==== РАЗВЕДКА

Классы ;; Разбойник.
Требования ;; Ловкость 2 или выше.

Вы— искусный разведчик.

Ученик ;; Вы умеете использовать преимущества рельефа.
Если вы провалили бросок на Ловкость (Скрытность), вы можете его перебросить, однако этот результат уже засчитывается обязательно.
Подмастерье ;; Вы умеете появляться неожиданно для своих врагов.
Вы используете приём Перехват инициативы (Seize the Initiative) за 2 SP, а не 4, как обычно.

'''

[discrete]
==== СТИЛЬ БОЯ С ОРУЖИЕМ В ОДНОЙ РУКЕ

Классы ;; Разбойник и Воин.
Требования ;; Восприятие 2 или выше.

Вы хорошо сражаетесь в ближнем бою, держа оружие только в основной руке.

Ученик ;; Подобный стиль боя требует немалой осторожности.
Если вы используете действие активации, вы получаете +1 к Защите до конца боевой сцены, пока сражаетесь с оружием в одной руке.
Подмастерье ;; И одно оружие может превратиться в непробиваемый щит.
Бонус к Защите, пока вы используете этот стиль, повышается до 2.

'''

[discrete]
==== МАГИЯ ДУХА

Классы ;; Маг.
Требования ;; Фокус Магии (Дух).

Вы познали тайны магии Духа.

Ученик ;; Вы получаете способность чуять настроение разумных существ в радиусе шести ярдов вокруг вас — это требует малого действия.
ДМ должен охарактеризовать это настроение одним словом (зол, растерян, или счастлив, например).
Подмастерье ;; Вы глубоко постигли принципы Магии Духа.
Когда вы творите заклинание Духа, оно стоит на 1 очко маны меньше, чем обычно, до минимума 1 очко.
Вы также получаете новое заклинание Духа.

'''

[discrete]
==== ВОРОВСТВО

Классы ;; Разбойник.
Требования ;; Ловкость 3 или выше.

Ваши вещи — это ваши вещи.
А их вещи скоро станут вашими тоже.

Ученик ;; Наличие замка вас не остановит.
Если провалили бросок на Ловкость (Взлом замка), вы можете перебросить его, однако этот результат обязаны оставить.
Подмастерье ;; Вам встречались самые разные ловушки.
Если вы провалили бросок на Ловкость (Ловушки), вы можете перебросить его, однако этот результат обязаны оставить.

'''

[discrete]
==== МЕТАТЕЛЬНОЕ ОРУЖИЕ

Классы ;; Разбойник или Воин.
Требования ;; Вы должны владеть оружием типа Топоры, Лёгкие клинки, или Копья.

Вы спец по метанию оружия.

Ученик ;; Ваша точность не поддаётся описанию.
Вы получаете бонус +1 ко всем броскам атаки метательным оружием.
Подмастерье ;; Вы выхватываете метательное оружие мгновенно.
Вы тратите на это свободное действие, а не дополнительное, как обычно.

'''

[discrete]
==== СТИЛЬ БОЯ С ДВУРУЧНЫМ ОРУЖИЕМ

Классы ;; Воин.
Требования ;; Сила 3 или выше, владение оружием типа Топоры, Дубины, Тяжёлые клинки или Копья.

Двуручное оружие в ваших руках сеет смерть и разрушение.

Ученик ;; Длина вашего оружия и сила атак отталкивает вашего противника назад.
Когда вы атакуете кого-то двуручным оружием в ближнем бою, вы можете сдвинуть цель на 2 ярда в любом направлении.
Подмастерье ;; Вы умеете наносить вашим оружием ужасные удары.
На приём Мощный Удар вы тратите 1 SP, а не 2, если дерётесь двуручным оружием.

'''

[discrete]
==== РУКОПАШНЫЙ БОЙ

Классы ;; Маг, Разбойник и Воин.
Требования ;; Владение оружием типа Рукопашная.

Вы знаете, как работать кулаками.

Ученик ;; У вас тяжёлая, как чугун, рука: удар кулаком причиняет 1к6 урона, а не 1к3.
Подмастерье ;; Ваши тумаки сшибают с ног даже самых крепких противников.
На приём Сбить с Ног вы тратите 1 SP, а не 2, если атакуете ударом кулака или перчатки.

'''

[discrete]
==== СТИЛЬ БОЯ С ОРУЖИЕМ И ЩИТОМ

Классы ;; Воин.
Требования ;; Сила 1 или выше.

Вы умело дерётесь в ближнем бою со щитом в одной руке и оружием— в другой.

Ученик ;; Вы можете использовать щиты различных форм и размеров.
Вы получаете полную Защиту, когда используете щит.
Подмастерье ;; Вы знаете, как по максимуму использовать преимущество, которое даёт вам щит.
Приём Защита стоит для вас 1 SP, а не 2, как обычно.

'''

[discrete]
==== ЗАСТОЛЬЕ

Классы:: Маг, Воин или Разбойник.
Требования:: Общение и Телосложение 1 или выше.

Вы серьёзно относитесь к веселью.

Ученик:: Вы можете пить, когда все остальные уже лежат под столом.
Делая броски на Телосложение (Выпивку) как часть расширенного броска, вы получаете бонус +1 к каждому кубику дракона, очки которого добавляете к общей сумме.
Это позволяет вам быстрее достичь порога успеха.
Подмастерье:: Таверна— ваш второй дом.
Выберите один из следующих фокусов: Азартная игра или Соблазнение.
Если вы провалили бросок на Общение с выбранным фокусом, вы можете перебросить его, однако обязаны оставить результат второго броска.
Мастер:: Когда вы веселитесь, вы неотразимы! (так, по крайней мере, вы думаете...) Выберите один из следующих социальных приёмов: флирт или железная воля.
Этот социальный приём вы можете использовать за 3 SP вместо обычных 4. Вы получаете бонус +1 на встречные броски, когда используете этот приём.
Таким образом, если вы использовали приём железная воля, бонус, который вы получаете на встречные броски, повышается до +2 (в обычных условьях он равен +1).

'''

[discrete]
==== ИНТРИГИ

Классы:: Маг, Воин и Разбойник
Требования:: Общение 2 или выше

Вы— мастер закулисных игр.

Ученик:: Вы знаете, как играть в Игру.
Выберите один из следующих фокусов Общения: Этикет, Обман или Соблазнение.
Если вы провалили бросок на Общение с этим фокусом, вы можете его перебросить, однако обязаны оставить результат второго броска.
Подмастерье:: Вы всегда получаете больше информации, чем вам говорят.
На социальный приём и ещё вы тратите 1 SP, а не 2. В добавок к тому, вы получаете бонус +1 ко всем остальным броскам, которые позволяет сделать этот приём.
Мастер:: Вы знаете, как завершить беседу.
Вы тратите на социальный приём ошеломлённое молчание 2 SP вместо обычных 3. В добавление к тому вы можете использовать его во время боя.
При этом вы и один союзник за каждое потраченное вами очко приёма сверх нормы могут действовать в первом раунде боя.
Все остальные считаются застигнутыми врасплох.

'''

[discrete]
==== СТИЛЬ БОЯ ВЕРХОМ

Класс:: Воин
Требования:: фокус Ловкости (Верховая езда).

Вы— искусный кавалерист.
Примечание: Двуручное оружие и длинные луки нельзя использовать во время боя верхом (это правило действует на всех, не только на тех, у кого есть этот талант).
Если вы всё-таки используете это оружие, оно считается импровизированным.

Ученик:: В бою вы извлекаете максимум выгоды из подвижности своего скакуна.
Когда вы, будучи на коне, используете действия движения, вы можете преодолеть часть положенного расстояния, сделать атаку ближнего боя или дальнобойную атаку, и преодолеть оставшееся расстояние.
Максимальное расстояние, которое вы можете преодолеть, равно Скорости вашего скакуна.
В обычных условьях вы должны завершить движение до того, как начали атаку.
Подмастерье:: Ваши стремительные атаки внушают ужас врагам.
Во время стремительной атаки вы можете преодолеть расстояние, равное полной Скорости своего скакуна, и причиняете на 1 больше урона, если попали в цель.
Мастер:: Вы и ваш скакун-- единое целое.
Вас невозможно сбить с коня с помощью приёма сбить с ног.

'''

[discrete]
==== НАБЛЮДЕНИЕ

Классы:: Маг, Разбойник и Воин.
Требования:: Восприятие 3 или выше.

Ваш глаз подмечает мельчайшие детали.

Ученик:: Вы замечаете вещи, которые не замечают остальные.
Выберите один из следующих фокусов: Эмпатия или Зоркость.
Если вы провалили бросок на Восприятие с выбранным фокусом, вы можете перебросить его, однако результат второго броска должны оставить.
Подмастерье:: Анализируя увиденное, вы всегда видите сущность вещей.
На исследовательский приём интересно вы тратите 2 SP вместо обычных 3.
Мастер:: Ничто не ускользнёт от вашего внимательного взора.
Вы тратите на исследовательский приём предмет внимания 2 SP вместо обычных 3. В дополнение ко всему приём даёт вам бонус +2 вместо обычного +1.

'''

[discrete]
==== ОРАТОР

Класс:: Маг, Разбойник и Воин.
Требования:: фокус Общения (Убеждение).

Вы умелый оратор, чьи слова имеют власть над умами людей.

Ученик:: Вы знаете, как управлять толпой.
Если вы провалили бросок на Общение (Убеждение), пытаясь убедить некоторое количество людей, вы можете перебросить его, однако второй результат должны оставить.
Вы не можете перебросить бросок, если находитесь в приватной обстановке или пытаетесь убедить одного человека.
Подмастерье:: Ваши слова сродни магии.
Каждый раз, когда вы используете социальный приём управлять толпой, его эффект распространяется на три дополнительных человека вместо одного.
Мастер:: Вы можете увлечь толпу за собой.
Если вы делаете успешный бросок на Общение (Убеждение), общаясь с несколькими людьми, и результат вашего кубика дракона 5 или 6, вы побуждаете их на незамедлительные действия.
Вы не всегда можете контролировать их действия, однако они принимают ваши слова близко к сердцу и действуют в соответствии с ними.

'''

[discrete]
==== СТИЛЬ БОЯ С ДРЕВКОВЫМ ОРУЖИЕМ

Классы:: Воин
Требования:: Вы должны владеть оружием типа Древковое или Копья.

Древковое оружие может быть неуклюжим, но не в ваших руках.
Вы умеете драться двуручным копьём или любым оружием типа Древковое.

Ученик:: Вы умеете извлекать выгоду из длинны своего оружия.
Вы можете атаковать врагов, которые находятся на расстоянии 4 ярдов от вас, как будто они с вами соседствуют (они не могут делать то же самое, если только у них нет этого же таланта).
Вы можете атаковать, даже если между вами и противником находится союзник.
По сути дела, это и есть основная тактика.
Подмастерье:: Когда вы подготовились, вас не сдвинуть с места.
Использовав действие активации, вы можете занять боевую стойку.
После этого до конца сцены, если противник используют приём рывка (или возможность, которую даёт ранг новичка в таланте Стиль Боя с Двуручным Оружием), он и вы должны сделать встречный бросок на атаку.
Если вы выигрываете, то противнику не удалось подвинуть вас и он в пустую тратит очки приёмов.
Если выиграет противник, то он может применит приём (или приёмы) рывка.
Мастер:: Вы по максимуму используете особенности своего оружия.
Если вы дерётесь боевым трезубцем или двуручным копьём, приём пробить броню стоит для вас 1 SP, а не 2, как обычно.
Если вы дерётесь глефой (glaive) или алебардой (halberd), приём сбить с ног стоит для вас 1 SP, а не 2, как обычно.
В добавление ко всему, противники, дерущиеся верхом, не получают бонуса +1, когда атакуют вас.

'''

[discrete]
==== НАЧЕРТАНИЕ РУН

Классы:: Маг, Разбойник (только гном), Воин (только гном).
Требования:: Гном или Усмирённый, Разум 3 и выше и фокус Магии (Зачарование).

Вы— искусный заклинатель, способный наносить руны на броню и оружие.

Ученик:: Вы можете нанести руну ученика на комплект брони или на оружие.
На это вам потребуется 2 часа.
Вы можете сделать это быстрее, если сделаете успешный бросок на Магию (Зачарование) против сложности 13. Каждый ранг успеха уменьшает время на 15 минут.
Например, если на Кубике Дракона у вас выпало 3, вы сделаете это на 45 минут быстрее.
Подмастерье:: Вы можете нанести руну подмастерья на комплект брони или оружие.
На это вам потребуется 3 часа.
Вы можете сделать это быстрее, если сделаете успешный бросок на Магию (Зачарование) против сложности 15. Каждый ранг успеха уменьшает время на 15 минут.
Мастер:: Вы можете нанести руну мастера на комплект брони или оружие.
На это вам потребуется 4 часа.
Вы можете сделать это быстрее, если сделаете успешный бросок на Магию (Зачарование) против сложности 17. Каждый ранг успеха уменьшает время на 15 минут.
