= ОРУЖИЕ И СНАРЯЖЕНИЕ

== ДОСПЕХИ И ЩИТЫ

И доспехи, и щиты защищают вас от повреждений, но различными способами.
Щиты уменьшают шанс попадания по вам, тогда как доспех поглощает нанесённый вам урон.
В зависимости от класса, вы либо не можете использовать ни то, ни другое, либо одно из двух, либо и доспехи, и щит.
Воины и разбойники имеют опыт ношения доспехов изначально, и первые обычно щеголяют в лучшей броне, которую могут себе позволить.
Нормально использовать щит могут только те, кто владеют талантом Стиль боя с Оружием и Щитом– этот стиль боя распространен среди воинов больше всего.
Те, кто предпочитает двуручное оружие или стрелковое, обычно щит не используют.

[caption="Таблица 12. "]
.ДОСПЕХИ
[cols="~,~,~,~"]
|===
|Броня |Класс брони |Штраф за броню |Цена
|Лёгкая кожаная |3 |0| 15 см
|Тяжёлая кожаная| 4| -1| 30 см
|Лёгкая кольчуга| 5 |-2| 50 см
|Тяжёлая кольчуга |7 |-3 |75 см
|Лёгкая латная |8| -4 |100 см
|Тяжёлая латная |10 |-5 |150 см
|===

[caption="Таблица 12. "]
.ЩИТЫ
[cols="~,~,~,~"]
|===
|Щит |Бонус щита |Цена
|Лёгкий щит |+1 |15 см
|Средний щит |+2 |30 см
|Тяжёлый щит |3 |60 см
|===

== ВЛАДЕНИЕ ОРУЖИЕМ

Оружие распределено по типам, владение которыми вы получаете в зависимости от класса.
Если вы владеете типом оружия, вы можете использовать любое относящееся к нему оружие, которое хватит сил поднять.
Если вы не владеете типом оружия, то получаете штраф -2 к броскам атаки этим оружием и наносите только половину урона (округление вниз), когда атакуете им в бою.
Если это дальнобойное оружие, то дальность также уменьшается вдвое.
Бонус силы добавляется до упомянутого разделения на два, а не после.

== СТРЕЛКОВОЕ ОРУЖИЕ

Стрелковое оружие позволяет делать дальнобойные атаки.
К нему относится и то оружие, из которого нужно стрелять, и то, что нужно метать.
Оно обладает несколькими особыми характеристиками из-за специфики дальнобойных атак, приведенными в таблице Дальности Стрелкового Оружия.
Каждое стрелковое оружие обладает следующими характеристиками:

Малая дальность (Short Range):: Если цель находится в пределах этой дальности то вы атакуете, как обычно.
Большая дальность (Long Range):: Если ваша цель находится в пределах этой дальности, но дальше, чем указывает малая, то ваша дальнобойная атака получает штраф -2.
Перезарядка:: После того, как вы сделали дальнобойную атаку, вам нужно перезарядить оружие, прежде чем снова из него стрелять.
На перезарядку требуется действие, это может быть как основное, так и дополнительное, так и свободное действие– зависит от вашего оружия и талантов.
Данная колонка таблицы указывает, какое действие нужно потратить на перезарядку каждого оружия.
Наличие талантов может изменить эту характеристику.

[caption="Таблица 12. "]
.ОРУЖИЕ
[cols="~,~,~,~"]
|===
|Оружие |Урон |Мин. Сила |Цена
4+|Тип: Топоры (Сила)
|Боевой топор (Battle Axe) |2к6| 1| 14см
|Метательный топор (Throwing Axe) |1к6+2| 1| 10 см
|Двуручный топор (Two-handed Axe) |3к6| 3| 20 см
4+|Тип: Дробящее (Сила)
|Булава (Mace) |2к6| 1 |12 см
|Молот (Maul) |1к6+3| 1| 4 см
|Двуручный молот (Two-handed Maul) |2к6+3| 3| 19 см
4+|Тип: Луки (Ловкость)*
|Арбалет (Crossbow)| 2к6+1 |1 |20 см
|Короткий лук (Short Bow)| 1к6+1 |-1| 9 см
|Длинный лук (Long Bow) |1к6+3 |1| 15 см
4+|Тип: Рукопашная (Ловкость)
|Кулак (Fist) |1к3||
|Латная рукавица (Gauntlet)| 1к3+1| | 4 см
|Импровизировнное оружие (Improvised Weapon)|1к6-1 ||

4+|Тип: Тяжёлые клинки (Сила)

|Меч-бастард (Bastard Sword)| 2к6+1| 2| 20 см
|Длинный меч (Long Sword) |2к6 |1 |18 см
|Двуручный меч (Two-handed Sword)| 3к6 |3| 23 см

4+|Тип: Лёгкие клинки (Ловкость)

|Кинжал (Dagger) |1к6+1| -| 9 см
|Короткий меч (Short Sword) |1к6+2| -1| 14 см
|Метательный нож (Throwing Knife)| 1к6| -| 10 см

4+|Тип: Копья (Сила)

|Копьё (Spear) |1к6+3 |0 |12 см
|Метательное копьё (Throwing Spear)| 1к6+3| 0| 12 см
|Двуручное копьё (Two-handed Spear)| 2к6| 1| 20 см

4+|Тип: Посохи (Ловкость)

|Дубина (Club)| 1к6 |- |1 см
|Моргенштерн (Morningstar) |1к6+3 |1 |11 см
|Посох (Quarterstaff) |1к6+1| 1 |3 см
|===

== ДАЛЬНОСТЬ СТРЕЛКОВОГО ОРУЖИЯ

[caption="Таблица 12. "]
.ДАЛЬНОСТЬ ОРУЖИЯ
[cols="~,~,~,~"]
|===
|Оружие| Малая дальность |Высокая дальность |Перезарядка (действие)
|Арбалет |30 ярдов |60 ярдов |Основное
|Длинный лук| 26 ярдов |52 ярда |Дополнительное
|Короткий лук| 16 ярдов| 32 ярда| Дополнительное
|Метательный топор| 4 ярда| 32 ярда| Дополнительное
|Метательный нож| 6 ярдов| 12 ярдов| Дополнительное
|Метательное копьё| 8 ярдов| 16 ярдов| Дополнительное
|===

== ЯДЫ И ГРАНАТЫ

В таблице описываются основные токсины и взрывчатка, которые можно найти на Тедасе.
В описании каждой представлены следующие характеристики:

Урон:: Обычный урон, который причиняет яд или граната.
Урон от яда всегда проникающий, если не описано иначе (урон от гранат обычно поглощается бронёй).
Дополнительные эффекты:: проявляющиеся не сразу и необычные эффекты яда или гранаты; ниже, в секции описания ядов, они рассматриваются подробно.
Цена:: обычная цена ингредиентов, необходимых для создания порции яда или гранаты, после которой следует обычная цена уже готовой дозы яда или гранаты.
Насколько доступен подобный вариант, решает ДМ, поскольку большинство ингредиентов открыто не купишь, и лишь очень малая часть из них пригождается в быту или какой-либо законной деятельности.

[caption="Таблица 12. "]
.ЯДЫ
[cols="~,~,~,~"]
|===
|Яд |Урон |Дополнительные эффекты |Цена
4+|Уровень: Ученик
|Яд Воронов (Crow Poison)| 1к6 |- |20 см / 1 зм
|Эксракт Корня Смерти (Deathroo Extract) |- |Галлюцинации |5 см / 25 см
|Порошок Целителя (Hale’s Dust) |-| -2 Сила |10 см / 50 см
|Яд паука (Spider Venom) |- |-2 Ловкость |10 см / 50 см
4+|Уровень: Подмастерье
|Поцелуй Гадюки (Adder’s Kiss) |2к6+4 |-| 1 зм / 5 зм
|Концентрированный Яд Воронов (Concentrated Crow Poison) |2к6 |Отложенная инициатива,
нельзя использовать приёмы |70 см / 350 см
|Концентрированный Яд Паука
(Concentrated Spider Venom) |- |-4 Ловкость |60 см / 3 зм
|Гниющая плоть (Fleshrot) |1к6| Из-за боли теряет действие |80 см / 4 зм
|Проклятье Магов (Magebane) |-| Потеря 2к6 очков маны |80 см / 4 зм
4+|Уровень: Мастер
|Концентрированое Проклятье Магов (Concentrated Magebane) |- |Потеря 4к6 очков маны |130 см / 650 см
|Оковы Плоти (Marrow Lock) |-|Выполнение Основных действий затруднено и причиняет боль|150 см / 750 см
|Тихая Смерть (Quiet Death) |2к6| Здоровье падает до 0 |2 зм / 10 зм
|===

== ИСПОЛЬЗОВАНИЕ ГРАНАТ

Механика работы гранат совсем иная, чем ядов или обычных дальнобойных атак.
Вам не обязательно точно поразить цель; достаточно попасть в точку недалеко от неё, чтобы её задело взрывом.
Все гранаты-- дальнобойное оружие с малой дальностью 4 ядра и высокой-- 8 ярдов.
Атаки гранатами совершаются следующим образом:

1. Чтобы использовать гранату, вам нужно сначала потратить действие подготовки, чтобы приготовить её к использованию.
Если вы не бросили гранату в тот же раунд, что и приготовили её, против вас может быть использован приём Бабах! (см.
Вооружён и очень опасен).
2. Вы должны выбрать цель, находящуюся не далее 8 ярдов от вас.
Вам не обязательно её видеть, но добросить до неё гранату должно быть возможно: например, вы можете бросить снаряд за угол, но не через каменную стену.
3. Когда граната подготовлена, вы можете использовать действие броска (lob) (см. главу Игра), чтобы бросить её.
4. Метая гранату, сделайте бросок на Ловкость (Гранаты) против сложности 11. ДМ может повысить сложность для трудных бросков- например, если персонаж попытается кинуть гранату в маленькое окно.
5. Все, кто оказался в радиусе 2х ярдов от центра взрыва-- что союзники, что противники-- получают урон от гранаты.
Атакуя гранатой, вы можете использовать следующие приёмы: Защитная Стойка, Сбить с Ног, Смертельный Удар, Мощный Удар, Пробивание Брони, Перехват Инициативы, Бросок, Быть Настороже, Угроза и Насмешка.
Каждый приём воздействует только на одну цель, но если граната поражает нескольких, не обязательно, чтобы все приёмы действовали на одного противника.
Например, если вы задели гранатой двух порождений тьмы, вы можете использовать приём Пробивание Брони против одного, и Сбить с Ног--против второго.

[caption="Таблица 12. "]
.ГРАНАТЫ
[cols="~,~,~,~"]
|===
|Граната |Урон |Эффект |Цена
4+|Уровень: Подмастерье
|Флакон кислоты (Acid Flask) |3к6 |Уменьшает Броню |40 см / 2 зм
|Огненная Бомба (Fire Bomb) |3к6| Поджигает |40 см / 2 зм
|Морозная Бомба (Freeze Bomb) |3к6| -3 Скорость |40 см / 2 зм
|Шоковая бомба (Shock Bomb) |2к6| Проникающий урон при металлической броне |40 см / 2 зм
|===
