=== ФОКУСЫ СПОСОБНОСТЕЙ

Фокус– совокупность умений, расположенная внутри сферы деятельности, которую охватывает способность.
Тогда как Разум определяет, насколько сообразителен ваш персонаж, фокус Геральдика, например, даст ему особые знания об обмундировании солдат и знатных семьях.
В переводе на игровую механику, если у вас есть фокус, то, когда вы действуете в его рамках, соответствующая способность повышается на 2.


Фокусы Силы:: Топоры, Дробящее, Лазанье, Вождение, Тяжёлые клинки, Запугивание, Прыжки, Пики, Мощь, Древковое, Копья, Кузнечное дело.

Фокусы Ловкости:: Акробатика, Луки, Рукопашная, Каллиграфия, Инициатива, Ловкость рук, Лёгкие клинки, Взлом замков, Верховая езда, Посохи, Скрытность, Ловушки, Ремесло, Дуэльное, Гранаты.

Фокусы Телосложения:: Выпивка, Гребля, Бег, Выносливость, Плавание.

Фокусы Восприятия:: Эмпатия, Слух, Поиск, Зоркость, Нюх, Выслеживание.

Фокусы Разума:: Знание Магии, Картография, Знание Культуры, Техника, Оценка, Лечение, Геральдика, Знание Истории, Знание Военного дела, Знание Музыки, Знание Природы, Навигация, Научные Исследования, Знание Религии, Литература, Варка, Криптография, Знание ядов, Кун.

Фокусы Магии:: Волшебный жезл, Созидание, Зачарование, Энтропия, Элементы, Дух, Кровь.

Фокусы Воли:: Отвага, Вера, Мораль, Самоконтроль.

Фокусы Общения:: Обращение с животными, Торговля, Обман, Маскировка, Этикет, Азартные игры, Расследование, Лидерство, Выступление, Убеждение, Соблазнение.
