=== ФОКУСЫ СПОСОБНОСТЕЙ

Фокус — мастерство в одной из сфер, которые охватывает способность.
Герой с Общением 3 и фокусом Обмана вообще хорошо ладит с людьми, но обманывает их ещё лучше.
Если у вас есть фокус, вы получаете бонус +2, когда совершаете бросок на соответствующую способность и действуете в рамках фокуса.
ДМ обычно объясняет, какие броски получают бонус, и от каких фокусов, но не бойтесь напомнить ему об этом, если он вдруг, по вашему мнению, забыл.

Фокусы Силы:: Топоры, Дробящее, Лазанье, Вождение, Тяжёлые клинки, Запугивание, Прыжки, Пики, Мощь, Древковое, Копья, Кузнечное дело.

Фокусы Ловкости:: Акробатика, Луки, Рукопашная, Каллиграфия, Инициатива, Ловкость рук, Лёгкие клинки, Взлом замков, Верховая езда, Посохи, Скрытность, Ловушки, Ремесло, Дуэльное, Гранаты.

Фокусы Телосложения:: Выпивка, Гребля, Бег, Выносливость, Плавание.

Фокусы Восприятия:: Эмпатия, Слух, Поиск, Зоркость, Нюх, Выслеживание.

Фокусы Разума:: Знание Магии, Картография, Знание Культуры, Техника, Оценка, Лечение, Геральдика, Знание Истории, Знание Военного дела, Знание Музыки, Знание Природы, Навигация, Научные Исследования, Знание Религии, Литература, Варка, Криптография, Знание ядов, Кун.

Фокусы Магии:: Волшебный жезл, Созидание, Зачарование, Энтропия, Элементы, Дух, Кровь.

Фокусы Воли:: Отвага, Вера, Мораль, Самоконтроль.

Фокусы Общения:: Обращение с животными, Торговля, Обман, Маскировка, Этикет, Азартные игры, Расследование, Лидерство, Выступление, Убеждение, Соблазнение.
