=== ФОКУСЫ СПОСОБНОСТЕЙ

Фокус– совокупность умений, расположенная внутри сферы деятельности, которую
охватывает способность. Тогда как Разум определяет, насколько сообразителен ваш
персонаж, фокус Геральдика, например, даст ему особые знания об обмундировании солдат и
знатных семьях. В переводе на игровую механику, если у вас есть фокус, то, когда вы
действуете в его рамках, соответствующая способность повышается на 2. Более детально это
разъясняется в Главе 6: Игра.
Фокусы способностей (или просто фокусы) – одна из вещей, которые создают уникальность
персонажа. В вашей партии приключенцев может быть два воина, но их фокусы будут в
корне отличаться. Пока вам не нужно задумываться о фокусах; очередь этого придёт позже, в
процессе создания персонажа. Ваш персонаж будет получать фокусы в зависимости от
биографии, класса и талантов. Больше информации о фокусах вы найдёте в Главе 3: Фокусы
и таланты.
Ниже перечислены фокусы, представленные в первом сете. Остальные ищите в следующих
сетах.

• Фокусы Силы: Топоры (Axes), Дробящее (Bludgeons), Лазанье (Climbing), Вождение
(Driving), Тяжёлые клинки (Heavy Blades), Запугивание (Intimidation), Прыжки
(Jumping), Мощь (Might), Копья (Spears).
• Фокусы Ловкости: Акробатика (Acrobatics), Луки (Bows), Рукопашная (Brawling),
Каллиграфия (Calligraphy), Инициатива (Initiative), Ловкость рук (Legerdemain),
Лёгкие клинки (Light Blades), Взлом замков (Lock Picking), Верховая езда (Riding),
Посохи (Staves), Скрытность (Stealth), Ловушки (Traps).
• Фокусы Телосложения: Выпивка (Drinking), Гребля (Rowing), Бег (Running),
Выносливость (Stamina), Плавание (Swimming).
• Фокусы Восприятия: Эмпатия (Empathy), Слух (Hearing), Поиск (Searching),
Зоркость (Seeing), Нюх (Smelling), Выслеживание (Tracking).
• Фокусы Разума: Знание Магии (Arcane Lore), Картография (Cartography), Знание
Культуры (Cultural Lore), Техника (Engineering), Оценка (Evaluation), Лечение
(Healing), Геральдика (Heraldry), Знание Истории (Historical Lore), Знание Военного
дела (Military Lore), Знание Музыки (Musical Lore), Знание Природы (Natural Lore),
Навигация (Navigation), Научные Исследования (Research), Знание Религии (Religious
Lore), Литература (Writing).
• Фокусы Магии: Волшебный жезл (Arcane Lance), Созидание (Creation), Энтропия
(Entropy), Элементы (Primal), Дух (Spirit).
• Фокусы Воли: Отвага (Courage), Вера (Faith), Мораль (Morale), Самоконтроль (Self-
Discipline).
• Фокусы Общения: Обращение с животными (Animal Handling), Торговля
(Bargaining), Обман (Deception), Маскировка (Disguise), Этикет (Etiquette), Азартные
игры (Gambling), Расследование (Investigation), Лидерство (Leadership), Выступление
(Performance), Убеждение (Persuasion), Соблазнение (Seduction).
