= ПОЛУЧЕНИЕ УРОВНЯ

[caption="Таблица 3. "]
.Продвижение по уровням (Level Advancement)
|===
|Всего опыта| Уровень
|0
|1
|2,000
|2
|4,000
|3
|6,000
|4
|8,000
|5
|10,000
|6
|13,000
|7
|16,000
|8
|19,000
|9
|22,000
|10
|25,000
|11
|28,000
|12
|32,000
|13
|36,000
|14
|40,000
|15
|44,000
|16
|48,000
|17
|52,000
|18
|56,000
|19
|60,000
|20
|===

Ваш персонаж получает очки опыта, преодолевая испытания, попадая в приключения,
побеждая врагов и достигая поставленных целей. Под завершении каждого приключения ДМ
награждает вас некоторым количеством очком опыта (сокращённо ХР– от англ. experience),
которые вам нужно записать на ваш лист персонажа. Полученные очки опыта складываются,
и когда их накапливается достаточно, ваш персонаж получает новый уровень. В этот момент
происходят следующие вещи:

• Здоровье вашего персонажа повышается на 1к6 + Телосложение.
• Вы можете повысить одну из способностей героя на 1. На чётных уровнях вы должны
повышать основные способности; на нечётных– дополнительные.
• Вы можете взять новый фокус способности. На чётных уровнях вы должны брать
фокусы ваших основных способностей; на нечётных– дополнительных.
• Вы получаете доступ к классовым умениям нового уровня. Каким именно, указано в
описании класса.
