= СНАРЯЖЕНИЕ

Ваши персонажи ступают на путь приключенца, имея в наличие кое-что кроме этого славного имени.
По ходу игры у героя есть возможность приобрести снаряжение получше, но начинает он с самым простым.
Стремитесь улучшить снаряжение при первой же возможности.

Герой начинает игру со следующими вещами:

• Рюкзак.
• Одежда путешественника.
• Бурдюк с водой.
• Если вы маг, вы получаете одно оружие и жезл (wand) (для того, чтобы атаковать магическими разрядами).
• Если вы разбойник, вы получаете лёгкую кожаную броню и два оружия.
• Если вы воин, вы получаете тяжёлую кожаную броню и три оружия.
• Если вы выбираете лук или арбалет, то получаете колчан с 20 стрелами или болтами.
• Если у вас есть талант Стиль боя с оружием и щитом, вы получаете средний щит (medium shield).

Удостоверьтесь, что взяли оружие того типа, которым владеет ваш персонаж.
В противном случае вы будите получать штрафы, когда попытаетесь его использовать, – так что в том, чтобы таскать с собой лишний груз, смысла мало.
Также помните, что некоторое оружие требует Силу определённой величины или выше, и удостоверьтесь, что ваш герой достаточно силён, чтобы размахивать двуручным мечом или чем-то вроде.
Также хорошо было бы записать Класс Брони (Armor Rating) вашего доспеха на лист персонажа.
Это мера того, насколько хорошую защиту вам даёт броня, – фактор, который необходимо учитывать во время боя.
Вы также получаете *50+3к6* серебряных монет для покупки остального снаряжения.
