=== ЗНАЧЕНИЯ СПОСОБНОСТЕЙ
:toc: left

Чтобы задать начальное значение вашим способностям, бросьте кубики.
Вам понадобятся три шестигранных кубика (3к6).
Бросьте все три и сложите выпавшие числа друг с другом.
Например, если у вас выпало 3, 4 и 6, то ваш результат будет равен 13 (3+4+6=13).

Всего вы должны сделать восемь таких бросков, по одному на каждую способность.
На листке вашего персонажа вы найдёте раздел, где записаны все способности вашего персонажа– начиная с Силы и заканчивая Общением.
Начиная с первой позиции списка– Силы– делайте указанный бросок на каждую из способностей, и сверяйте результат с таблицей Значений Способностей, чтобы определить её начальную величину.
Результат 11, например, обозначает, что стартовое значение способности – 1. Закончив с Силой, переходите к Ловкости, и так пока не будут заданы стартовые значения всем восьми способностям.

Когда закончите, можете поменять местами значения двух способностей.
Это даёт вам возможность немного приспособить персонажа под свои нужды.

[caption="Таблица 1. "]
.ЗНАЧЕНИЯ СПОСОБНОСТЕЙ
|===
|Бросок 3к6 |Стартовое значение
|3
|–2
|4
|–1
|5
|–1
|6
|0
|7
|0
|8
|0
|9
|1
|10
|1
|11
|1
|12
|2
|13
|2
|14
|2
|15
|3
|16
|3
|17
|3
|18
|4
|===

include::focus.adoc[leveloffset=1]
