= БЕСТИАРИЙ

[discrete]
== ОХОТНИК

Способности (Фокусы)::

* 2 Сила (Топоры, Лазание)
* 1 Ловкость
* 2 Телосложение (Выпивка, Выносливость)
* 1 Восприятие (Зоркость, Выслеживание)
* 0 Разум
* 1 Воля (Мораль)
* 0 Магия
* 1 Общение (Обращение с животными)

[caption="Боевые характеристики"]
[cols="~,~,~,~"]
|===
|Скорость |Здоровье |Защита |Класс брони
|9 |20 |11 (13 со щитом) |3
|===

[caption="Атака"]
[cols="~,~,~"]
|===
|Оружие |Бросок атаки |Урон
|Боевой топор |+4 |2к6+2
|Длинный лук |+1 |1к6+4
|===

Любимые приёмы:: Мощный удар и Рывок

Таланты:: Дрессировка (Подмастерье), Опыт ношения брони (Ученик), Стиль боя с Оружием и Щитом (Ученик)
Типы оружия:: Топоры, Луки, Рукопашное и Копья
Снаряжение:: Боевой топор, лёгкая кольчуга, длинный лук, средний щит

[discrete]
== ЧЁРНЫЙ МЕДВЕДЬ

Способности (Фокусы)::

* 6 Сила (Когти, Запугивание, Мощь)
* 2 Ловкость (Укус)
* 6 Телосложение (Выносливость)
* 2 Восприятие (Нюх, Вкус)
* -1 Разум
* 2 Воля
* -1 Магия
* 0 Общение


Боевые характеристики::

[caption="Боевые характеристики"]
[cols="~,~,~,~"]
|===
|Скорость |Здоровье |Защита |Класс брони
|13 |60| 12 |0
|===

[caption="Атака"]
[cols="~,~,~"]
|===
|Оружие| Бросок атаки| Урон
|Укус |+4| 1к6+6
|Когти| +8| 2к6+6
|===

Любимые приёмы:: Сбить с Ног (1 SP) и Быстрый Укус
Быстрый Укус:: После успешной атаки когтями чёрный медведь может использовать приём Быстрого Укуса за 2 SP.
Укус должен иметь ту же цель, что и предыдущая атака.
Если при броске на укус на двух и более кубиках выпадают одинаковые числа, медведь не получает за это SP.

[discrete]
== БРОНТО

Способности (Фокусы)::

* 5 Сила (Рога, Мощь)
* 3 Ловкость
* 5 Телосложение (Выносливость)
* 2 Восприятие (Зоркость)
* -1 Разум
* 2 Воля
* 0 Магия
* -1 Общение

[caption="Боевые характеристики"]
[cols="~,~,~,~"]
|===
|Скорость |Здоровье |Защита |Класс брони
|12 |40 |13 |3
|===

[caption="Атака"]
[cols="~,~,~"]
|===
|Оружие| Бросок атаки| Урон
|Рога |+7 |2к6+5
|===

Любимые приёмы :: Мощный удар и Пробить Броню
Толстая шкура :: Толстая шкура даёт бронто класс брони, равный 3.

[discrete]
== ХАСИНДСКИЙ СТАЛКЕР

Способности (Фокусы)::

* 2 Сила (Лазание)
* 3 Ловкость (Луки, Лёгкие клинки, Скрытность)
* 2 Телосложение (Выносливость)
* 3 Восприятие (Поиск, Зоркость, Выслеживание)
* 1 Разум
* 1 Воля (Мораль)
* 1 Магия
* 0 Общение

[caption="Боевые характеристики"]
[cols="~,~,~,~"]
|===
|Скорость |Здоровье |Защита |Класс брони
|13 |20 |13 (14 со щитом) |3
|===

[caption="Атака"]
[cols="~,~,~"]
|===
|Оружие| Бросок атаки| Урон
|Короткий лук |+5 |1к6+4
|Короткий меч |+5 |1к6+4
|===

Любимые приёмы :: Пробить Броню и Рывок
Таланты:: Лучник (Подмастерье), Опыт Ношения Брони (Ученик), Разведка (Подмастерье)
Типы оружия:: Луки, Рукопашная, Лёгкие клинки
Снаряжение::
Лёгкий Кожаный Доспех, Лёгкий Щит, Короткий Лук и Короткий Меч

[discrete]
== ДОЛИЙСКИЙ РЕЙДЕР

Способности (Фокусы)::

* 1 Сила (Лазание)
* 3 Ловкость (Луки, Инициатива, Лёгкие клинки, Скрытность)
* 0 Телосложение
* 2 Восприятие (Слух, Выслеживание)
* 1 Разум (Знание природы)
* 3 Воля (Самоконтроль)
* 1 Магия
* 2 Общение (Убеждение)

[caption="Боевые характеристики"]
[cols="~,~,~,~"]
|===
|Скорость |Здоровье |Защита |Класс брони
|13 |16 |13 |5
|===

[caption="Атака"]
[cols="~,~,~"]
|===
|Оружие| Бросок атаки| Урон
|Длинный лук |+5 |1к6+4
|Короткий меч| +5| 1к6+3
|===

Любимые приёмы :: Молниеносная Атака и Быстрая Перезарядка
Таланты:: Лучник (Подмастерье), Опыт Ношения Брони (Ученик), Стиль боя с одним оружием (Подмастерье)
Типы оружия:: Луки, Рукопашная, Лёгкие клинки
Снаряжение::
Лёгкая Кольчуга, Длинный Лук, и Короткий Меч

[discrete]
== ГЕНЛОК ПОРОЖДЕНИЕ ТЬМЫ

Способности (Фокусы)::

* 3 Сила (Топоры, Запугивание)
* 1 Ловкость (Рукопашное)
* 2 Телосложение (Бег)
* 2 Восприятие (Нюх)
* 1 Разум (Знание военного дела)
* 2 Воля
* 2 Магия
* 0 Общение

[caption="Боевые характеристики"]
[cols="~,~,~,~"]
|===
|Скорость |Здоровье |Защита |Класс брони
|6 |22 |11 (13 со щитом)| 7
|===

[caption="Атака"]
[cols="~,~,~"]
|===
|Оружие| Бросок атаки| Урон
|Боевой топор |+5 |2к6+3
|Метательный топор |+5 |1к6+4
|===

Любимые приёмы :: Сбить с Ног и Мощный Удар
Сопротивление Магии:: Генлок получает бонус +2 к броскам на способности на сопротивление эффектам заклинаний или магических атак.
Таланты:: Опыт Ношения Брони (Подмастерье), Стиль боя с Оружием и Щитом (Ученик)
Типы оружия:: Топоры, Рукопашное, Дробящее
Снаряжение::
Боевой Топор, Тяжёлая Кольчуга, Средний Щит и Метательный Топор

[discrete]
== ГАРЛОК ПОРОЖДЕНИЕ ТЬМЫ

Способности (Фокусы)::

* 4 Сила (Тяжёлые Клинки, Запугивание)
* 2 Ловкость (Рукопашная)
* 3 Телосложение (Выносливость)
* 2 Восприятие (Нюх)
* 1 Разум
* 3 Воля (Отвага, Мораль)
* 1 Магия
* 0 Общение

[caption="Боевые характеристики"]
[cols="~,~,~,~"]
|===
|Скорость |Здоровье |Защита |Класс брони
|8 |30 |12 |8
|===

[caption="Атака"]
[cols="~,~,~"]
|===
|Оружие| Бросок атаки| Урон
|Короткий лук |+2 |1к6+5
|Двуручный меч |+6 |3к6+4
|===

Яростная атака :: Гарлоки могут использовать приём Двойного Удара за 3 SP вместо обычных 4, если используют оружие ближнего боя.
Любимые приёмы :: Двойной Удар и Мощный Удар
Таланты:: Опыт Ношения Брони (Подмастерье), Стиль боя с Двуручным Оружием (Ученик), Стиль боя с Оружием и Щитом (Ученик)
Типы оружия:: Луки, Рукопашная, и Тяжёлые клинки
Снаряжение::
Лёгкие Латы, Короткий Лук и Двуручный Меч

[discrete]
== ДРАКОНЧИК

Способности (Фокусы)::

* 2 Сила (Когти, Прыжки)
* 5 Ловкость (Инициатива)
* 2 Телосложение (Бег)
* 3 Восприятие (Зоркость)
* 25
* -1 Разум
* 1 Воля
* 0 Магия
* -1 Общение

[caption="Боевые характеристики"]
[cols="~,~,~,~"]
|===
|Скорость |Здоровье |Защита |Класс брони
|16 |15| 15| 3
|===

[caption="Атака"]
[cols="~,~,~"]
|===
|Оружие| Бросок атаки| Урон
|Укус |+5 |1к6+2
|Когти |+4 |2к6+2
|Огненное дыхание |+5 |2к6
|===

Любимые приёмы :: Мощный Удар и Пробивание Брони
Огненное дыхание :: Дракончик может выдыхать пламя, что считается дальнобойной атакой.
Малая дальность Огненного Дыхания равна 6 ярдам, а высокая дальность– 12.
Приём Быстрого Укуса :: Сделав успешную атаку когтями, дракончик может использовать приём Быстрого Укуса, который стоит 2 SP.
Укус должен иметь ту же цель, что предшествующая ему атака.
Если при этом броске на двух и более кубиках выпадают одинаковые результаты, дракончик не получает очков приёмов.
Крепкая Шкура :: Чешуя дракончиков даёт им класс брони, равный 3

[discrete]
== ФЕРЕЛДЕНСКИЙ БАНДИТ

Способности (Фокусы)::

* 2 Сила (Лазание)
* 2 Ловкость (Ловкость рук, Лёгкие клинки, Скрытность)
* 1 Телосложение (Выпивка)
* 1 Восприятие (Зоркость)
* 0 Разум (Оценка)
* 0 Воля
* 0 Магия
* 2 Общение (Обман, Азартные Игры)

[caption="Боевые характеристики"]
[cols="~,~,~,~"]
|===
|Скорость |Здоровье |Защита |Класс брони
|12 |18 |12 |3
|===

[caption="Атака"]
[cols="~,~,~"]
|===
|Оружие| Бросок атаки| Урон
|Кинжал |+4 |1к6+3
|Короткий лук |+2| 1к6+2
|Короткий меч |+4 |1к6+4
|===

Любимые приёмы :: Молниеносный Удар и Рывок
Таланты:: Опыт Ношения Брони (Ученик), Стиль боя с Двумя Оружиями (Подмастерье), Разведка (Ученик)
Типы оружия:: Луки, Рукопашная, и Лёгкие клинки
Снаряжение::
Кинжал, Лёгкая Кожаная Броня, и Короткий Лук

[discrete]
== БОЕВОЙ ПЁС МАБАРИ

Способности (Фокусы)::

* 2 Сила (Прыжки)
* 3 Ловкость (Укус)
* 2 Телосложение (Бег)
* 2 Восприятие (Нюх, Выслеживание)
* -1 Разум
* 1 Воля (Мораль)
* -1 Магия
* 0 Общение

[caption="Боевые характеристики"]
[cols="~,~,~,~"]
|===
|Скорость |Здоровье |Защита |Класс брони
|16 |25 |13 |0
|===

[caption="Атака"]
[cols="~,~,~"]
|===
|Оружие| Бросок атаки| Урон
|Укус |+5 |1к6+4
|===

Любимые приёмы :: Сбить с Ног и Мощный Удар

[discrete]
== СКЕЛЕТ ДЕМОН ГНЕВА

Способности (Фокусы)::

* 3 Сила (Когти)
* 2 Ловкость
* 2 Телосложение (Выносливость)
* 0 Восприятие
* -2 Разум
* 2 Воля
* 1 Магия
* -2 Общение

[caption="Боевые характеристики"]
[cols="~,~,~,~"]
|===
|Скорость |Здоровье |Защита |Класс брони
|10 |17 |12| 0
|===

[caption="Атака"]
[cols="~,~,~"]
|===
|Оружие| Бросок атаки| Урон
|Лук |+2 |1к6+6
|Двуручный меч |+3| 2к6+3
|Когти |+5 |1к6+5
|===

Любимые приёмы :: Могучий Удар и Пробивание Брони
Буйное Безумие :: Демон, который вселился в скелет, безумен.
Все броски на Волю (Мораль), которые ему может потребоваться сделать, удаются автоматически.
Типы Оружия :: Дробящее, Луки и Копья
Снаряжение ::
Двуручное Копьё или Лук

[discrete]
== КЛЫКАСТЫЙ СКЕЛЕТ ДЕМОН ГОЛОДА

Способности (Фокусы)::

* 3 Сила (Когти, Тяжёлые Клинки)
* 2 Ловкость (Укус)
* 3 Телосложение (Выносливость)
* 0 Восприятие
* -1 Разум
* 2 Воля
* 2 Магия
* -2 Общение

[caption="Боевые характеристики"]
[cols="~,~,~,~"]
|===
|Скорость |Здоровье |Защита |Класс брони
|9 |22 |12 |4
|===

[caption="Атака"]
[cols="~,~,~"]
|===
|Оружие| Бросок атаки| Урон
|Укус |+4 |1к6+3
|Когти |+5| 1к6+5
|Длинный Меч |+5| 2к6+3
|===

Исцеление Кровью :: Когда клыкастый скелет кусает бессознательного или убитого врага, он восстанавливает 2к6 Здоровья за высосанную кровь.
Если приём используется против бессознательного врага, то он считается ударом милосердия.
Любимые приёмы :: Сбить с Ног и Могучий Удар.
Буйное Безумие :: Демон, который вселился в клыкастый скелет, безумен.
Все броски на Волю (Мораль), которые ему может потребоваться сделать, удаются автоматически.
Таланты:: Опыт Ношения Брони (Ученик) и Стиль боя с Одним Оружием (Ученик).
Типы Оружия :: Топоры, Лёгкие Клинки, и Тяжёлые Клинки
Снаряжение ::
Тяжёлый Кожаный Доспех и Длинный Меч

[discrete]
== РАЗЪЯРЁННЫЙ МЕРТВЕЦ ДЕМОН ГНЕВА

Способности (Фокусы)::

* 4 Сила (Когти, Запугивание)
* 0 Ловкость
* 4 Телосложение (Выносливость)
* 0 Восприятие
* 1 Разум
* 2 Воля
* 2 Магия
* -2 Общение

[caption="Боевые характеристики"]
[cols="~,~,~,~"]
|===
|Скорость |Здоровье |Защита |Класс брони
|8 |40 |10 |0
|===

[caption="Атака"]
[cols="~,~,~"]
|===
|Оружие| Бросок атаки| Урон
|Когти| +6 |1к6+6
|===

Любимые приёмы :: Обезоруживание и Удушение
Буйное Безумие :: Демон, который вселился в разъярённого мертвеца, безумен.
Все броски на Волю (Мораль), которые ему может потребоваться сделать, удаются автоматически.
Удушение :: Разъярённый мертвец может использовать в ближнем бою Удушение как специальный приём за 3 SP.
Жертва немедленно получает 1к6 проникающего урона.
Жертва может попробовать освободиться, когда придёт черёд её хода, сделав успешный бросок на Силу (Мощь) против Силы (Мощи) мертвеца.
Если бросок провален, то жертва снова получает 1к6 проникающего урона.
В свой ход разъяренный мертвец может продолжать душить жертву, используя основное действие.
Если он выигрывает встречный бросок на Силу (Мощь), то причиняет ещё 1к6 проникающего урона; иначе жертва вырывается на свободу.
Разъярённый мертвец может душить противника до тех пока продолжает выигрывать броски на Силу (Мощь).
Таланты:: Опыт Ношения Брони (Ученик) и Стиль боя с Одним Оружием (Ученик).
Типы Оружия :: Топоры, Лёгкие Клинки, и Тяжёлые Клинки
Снаряжение ::
Тяжёлый Кожаный Доспех и Длинный Меч

[discrete]
== МЕРТВЕЦ-ПОЖИРАТЕЛЬ ДЕМОН ГОЛОДА

Способности (Фокусы)::

* 3 Сила (Когти, Запугивание)
* 2 Ловкость
* 4 Телосложение (Выносливость)
* 0 Восприятие
* 0 Разум
* 2 Воля
* 2 Магия
* -2 Общение

[caption="Боевые характеристики"]
[cols="~,~,~,~"]
|===
|Скорость |Здоровье |Защита |Класс брони
|8 |30 |12| 0
|===

[caption="Атака"]
[cols="~,~,~"]
|===
|Оружие| Бросок атаки| Урон
|Когти |+5 |1к6+5
|===

Высасывание Жизни :: Мертвецы-пожиратели могут высосать жизнь из ближайшего противника, используя специальный приём за 5 SP.
Все враги в радиусе 6 ярдов вокруг мертвеца-пожирателя получают 1к6 проникающего урона, а он восстанавливает количество здоровья, равное сумме причинённого урона.
Любимые приёмы :: Высасывание жизни и Пробить броню
Буйное Безумие :: Демон, который вселился в разъярённого мертвеца, безумен.
Все броски на Волю (Мораль), которые ему может потребоваться сделать, удаются автоматически.

[discrete]
== КРЫСА, ГИГАНТСКАЯ

Способности (Фокусы)::

* 1 Сила
* 2 Ловкость (Укус, Скрытность)
* 2 Телосложение
* 2 Восприятие (Нюх)
* -2 Разум
* 1 Воля
* 0 Магия
* -3 Общение

[caption="Боевые характеристики"]
[cols="~,~,~,~"]
|===
|Скорость |Здоровье |Защита |Класс брони
|14 |12 |12| 0
|===

[caption="Атака"]
[cols="~,~,~"]
|===
|Оружие| Бросок атаки| Урон
|Укус |+4 |1к6+1
|===

Любимые приёмы :: Сбить с Ног и Могучий Удар
Все на Одного :: Гигантская крыса может применить особый приём Все на Одного, потратив на это 3 SP.
Это позволяет любой другой гигантской крысе сделать немедленную атаку по цели, если она с ней соседствует (находится не далее двух ярдов).
Если при броске на атаку на двух или более кубиках выпадут одинаковые значения, она не получает очков приёмов.
Гигантские крысы, которые ещё не делали ходов в текущем раунде, действуют, когда придёт их черёд, как обычно, даже если совершили бонусную атаку, которую предоставляет этот приём.

[discrete]
== ТЕНЬ

Способности (Фокусы)::

* -3 Сила
* 5 Ловкость (Скрытность)
* 0 Телосложение
* 1 Восприятие
* 0 Разум
* 4 Воля
* 4 Магия
* -2 Общение

[caption="Боевые характеристики"]
[cols="~,~,~,~"]
|===
|Скорость |Здоровье |Защита |Класс брони
|15 |30 |15 |0
|===

[caption="Атака"]
[cols="~,~,~"]
|===
|Оружие| Бросок атаки| Урон
|===

Иссушающее касание +5 1к6+4 проникающий

Иссушающая Аура :: За 4 SP тень может использовать особый приём Иссушающей Ауры.
Все противники в радиусе 4 ярдов получают 1к6 проникающего урона от того, что тень высасывает их жизненную энергию.
Иссушающее Касание :: Касание тени иссушает жизненную энергию жертвы.
Оно причиняет 1к6 + Магия проникающего урона.
Любимые приёмы :: Иссушающая Аура и Молниеносная Атака.
Бестелесный :: Тени бестелесны и их присутствие в материальном мире непрочно.
Особенности рельефа не оказывают на них никакого воздействия.
Как правило, только магические атаки (заклинания или удары магическим оружием) могут причинить им урон, остальное же оружие просто пройдёт сквозь них.
Атакующий персонаж может использовать специальный приём Разрушения Духа за 3 SP.
Оружие героя наносит обычный урон, однако к нему прибавляется бонус Магии, а не Силы, как обычно.
Например, персонаж с Магией 2, вооружённый длинным мечом, причинит тени 2к6+2 урона, используя Разрушение Духа.

[discrete]
== ГИГАНТСКИЙ ПАУК

Способности (Фокусы)::

* 3 Сила (Запугивание, Прыжки)
* 4 Ловкость (Укус, Скрытность)
* 3 Телосложение
* 3 Восприятие (Осязание)
* -2 Разум
* 1 Воля
* 0 Магия
* -1 Общение

[caption="Боевые характеристики"]
[cols="~,~,~,~"]
|===
|Скорость |Здоровье |Защита |Класс брони
|14 |35 |14 |5
|===

[caption="Атака"]
[cols="~,~,~"]
|===
|Оружие| Бросок атаки| Урон
|Укус |+6 |2к6+3
|===

Хитиновый панцирь :: Твёрдый панцирь гигантского паука даёт этому существу класс брони, равный 5.
Любимые приёмы :: Сбить с Ног и Ядовитый Укус (Poison Bit)
Ядовитый Укус :: Гигантский паук может впрыснуть в рану яд, потратив на этот особый приём 2 SP.
Яд ослабляет жертву, так что та получает штраф -2 к Ловкости до конца сцены, либо пока не будет исцелена магией (заклинание "исцеление").
Ползать по стенам :: Гигантские пауки могут передвигаться по стенам и по потолкам.
Паутина :: Использовав основное действие, гигантский паук может опутать паутиной противника, находящегося не далее 12 ярдов.
Цель должна сделать успешный бросок на Ловкость (Акробатику) против сложности 11 или застыть неподвижно.
Союзник может освободить цель заклинания, или она может освободиться сама, сделав успешный бросок на Силу (Мощь) против сложности 13. Это единственное действие, которое может предпринимать опутанная паутиной цель, пока не освободиться.

[discrete]
== МОРОВОЙ ВОЛК

Способности (Фокусы)::

* 2 Сила (Прыжки)
* 2 Ловкость (Укус, Скрытность)
* 3 Телосложение (Бег)
* 3 Восприятие (Слух, Нюх)
* -2 Разум
* 1 Воля
* 0 Магия
* 0 Общение

[caption="Боевые характеристики"]
[cols="~,~,~,~"]
|===
|Скорость |Здоровье |Защита |Класс брони
|10 |25 |12 |3
|===

[caption="Атака"]
[cols="~,~,~"]
|===
|Оружие| Бросок атаки| Урон
|Укус |+4 |1к6+4
|===

Любимые приёмы :: Сбить с Ног и Молниеносная Атака
Таланты:: Рукопашный бой (Подмастерье) Крепкая Шкура (Tough Hide): Костяные выросты на теле морового волка дают им Класс Брони, равный 3.

[discrete]
== ВУРДАЛАК ОСКВЕРНЁННЫЙ ПОРОЖДЕНИЯМИ

Способности (Фокусы)::

* 2 Сила (Дробящее, Запугивание)
* 2 Ловкость
* 2 Телосложение (Выносливость)
* 2 Восприятие
* -1 Разум
* 1 Воля (Мораль)
* 1 Магия
* 0 Общение

[caption="Боевые характеристики"]
[cols="~,~,~,~"]
|===
|Скорость |Здоровье |Защита |Класс брони
|10 |20 |12| 3
|===

[caption="Атака"]
[cols="~,~,~"]
|===
|Оружие| Бросок атаки| Урон
|Кулак |+2 |1к6+2
|Молот |+4 |1к6+5
|===

Безумные :: Упыри почти не обладают инстинктом самосохранения.
Если группа упырей проваливает бросок на Волю (Мораль), они могут его перебросить.
Однако второй результат они обязаны оставить.
Любимые приёмы :: Обезоруживание и Сбить с Ног
Таланты:: Рукопашный бой (Подмастерье)
Типы Оружия :: Дробящее и Рукопашная.
Снаряжение ::
Лёгкая Кожаная Броня

[discrete]
== БЕРЕСКАРН

Способности (Фокусы)::

* 7 Сила (Когти, Запугивание, Мощь)
* 3 Ловкость (Укус)
* 7 Телосложение (Выносливость)
* 3 Восприятие (Нюх, Выслеживание)
* -2 Разум
* 2 Воля (Отвага)
* -1 Магия
* -2 Общение

[caption="Боевые характеристики"]
[cols="~,~,~,~"]
|===
|Скорость |Здоровье |Защита |Класс брони
|13 |70 |13 |4
|===

[caption="Атака"]
[cols="~,~,~"]
|===
|Оружие| Бросок атаки| Урон
|Укус |+5 |1к6+7
|Когти |+9 |2к6+7
|===

Любимые приёмы :: Сбить с ног (1 SP), Быстрый Укус, Громовой Рык
Быстрый Укус:: Берескарн может использовать особый приём Быстрого Укуса за 2 SP, после того, как сделал удачную атаку.
Зверь делает дополнительную атаку-укус против той же цели.
Если при броске на эту атаку на двух и более кубиках выпадают одинаковые числа, берескарн не получает очков приёмов.
Громовой рык :: Потратив 3 SP, Берескарн может использовать приём Громового рыка.
Все, кто слышат его, должны сделать бросок на Волю (Отвагу или Самоконтроль) против Сложности 10 или потерять возможность атаковать берескарна до конца следующего раунда, хотя защищаться они могут, как обычно.
Крепкая шкура:: Костяные шипы берескарна дают зверю класс брони, равный 4.

[discrete]
== ВЕРВОЛЬФ

Способности (Фокусы)::

* 6 Сила (Когти, Запугивание)
* 4 Ловкость (Укус)
* 5 Телосложение (Бег)
* 3 Восприятие (Нюх, Выслеживание)
* 0 Разум
* 3 Воля (Отвага, Мораль)
* 1 Магия
* 0 Общение

[caption="Боевые характеристики"]
[cols="~,~,~,~"]
|===
|Скорость |Здоровье |Защита |Класс брони
|16 |50 |14 |4
|===

[caption="Атака"]
[cols="~,~,~"]
|===
|Оружие| Бросок атаки| Урон
|Укус |+6 |1к6+6
|Когти |+8 |2к6+6
|===

Любимые приёмы :: Опрокинуть (3 SP), Рывок, и Проклятье Вервольфа (количество SP варьируется).
Опрокинуть :: Вервольф может использовать особый приём за 3 SP, чтобы опрокинуть противника.
Зверь сбивает противника с ног и вонзает в него когти, что даёт вервольфу бонус +2 к дальнейшим атакам, пока противник пронзён его когтями (сюда включается обычный бонус +1 к атаке против сбитой с ног цели).
Противник должен сделать бросок на Силу (Мощь) против Силы (Мощь) вервольфа, чтобы освободиться; это требует дополнительного действия, и герой остаётся лежать на земле.
Попытку освободить жертву с соответствующим броском могут сделать и союзники жертвы, однако это потребует от них основного действия.
Проклятье вервольфа ::, Потратив SP после того, как успешно укусил цель, вервольф может заразить её проклятьем; цель должна сделать бросок на Телосложение (Выносливость) против сложности (10 + количество потраченных очков приёмов).
Проваленный бросок обозначает, что цель заражена.
Заражённая жертва вновь делает бросок на Телосложение (Выносливость) против той же сложности каждую ночь после того, как была укушена.
Если, после трёх ночей, ни один из этих бросков не удался, жертва превращается в вервольфа и больше не может быть игровым персонажем.
Шерсть:: Густая, клочковатая шерсть даёт вервольфам класс брони, равный 4.

[discrete]
== ГАЛЛА

Способности (Фокусы)::

* 4 Сила (Прыжки)
* 3 Ловкость
* 3 Телосложение (Бег, Выносливость)
* 3 Восприятие (Слух, Нюх)
* 0 Разум
* 2 Воля
* 2 Магия
* -1 Общение

[caption="Боевые характеристики"]
[cols="~,~,~,~"]
|===
|Скорость |Здоровье |Защита |Класс брони
|18 |35 |13| 0
|===

[caption="Атака"]
[cols="~,~,~"]
|===
|Оружие| Бросок атаки| Урон
|Рога |+4 |1к6+4
|Удар копытом |+4 |1к6+4
|===

Любимые приёмы :: Сбить с Ног и Растоптать (4 SP) Растоптать (Trample): После успешной атаки галла может использовать специальный приём Растоптать за 4 SP.
Цель в этом случае сбита с ног и получает дополнительные 1к6+4 урона от рогов галлы

[discrete]
== ГАРЛОК-ВОЖАК ПОРОЖДЕНИЕ ТЬМЫ

Способности (Фокусы)::

* 5 Сила (Тяжёлые Клинки, Запугивание, Мощь)
* 3 Ловкость (Луки, Рукопашная)
* 4 Телосложение (Выносливость)
* 2 Восприятие (Нюх)
* 2 Разум
* 3 Воля (Отвага, Мораль)
* 1 Магия
* 2 Общение (Лидерство)

[caption="Боевые характеристики"]
[cols="~,~,~,~"]
|===
|Скорость |Здоровье |Защита |Класс брони
|8 |70 |12 (15 со щитом) |8
|===

[caption="Атака"]
[cols="~,~,~"]
|===
|Оружие| Бросок атаки| Урон
|Короткий лук |+5 |1к6+3
|Двуручный меч |+7 |3к6+5
|Длинный меч |+7 |2к6+5
|===

Любимые приёмы :: Двойной Удар, Мощный Удар (1 SP), и Сплочение (3+ SP)
Сплочение :: Гарлок-вожак может использовать специальный приём Сплочения за 3 SP (или больше).
Действия вожака впечатляют и вдохновляют его войско: все порождения тьмы в радиусе 10 ядов, способные видеть вожака, восстанавливают количество Здоровья, равное Общению вожака плюс число потраченных SP.
Таланты:: Опыт Ношения Брони (Подмастерье), Бой Двуручным Оружием (Подмастерье) и Бой с Оружием и Щитом (Подмастерье).
Типы Оружия :: Мечи, Дробящее, и Тяжёлые клинки
Снаряжение ::
Лёгкие латы, короткий лук, и двуручный меч (или лёгкие латы, длинный меч и большой щит)

[discrete]
== ГАРЛОК-ВОЖАК ПОРОЖДЕНИЕ ТЬМЫ

Способности (Фокусы)::

* 5 Сила (Тяжёлые Клинки, Запугивание, Мощь)
* 3 Ловкость (Луки, Рукопашная)
* 4 Телосложение (Выносливость)
* 2 Восприятие (Нюх)
* 2 Разум
* 3 Воля (Отвага, Мораль)
* 1 Магия
* 2 Общение (Лидерство)

[caption="Боевые характеристики"]
[cols="~,~,~,~"]
|===
|Скорость |Здоровье |Защита |Класс брони
|8 |70 |12 (15 со щитом) |8
|===

[caption="Атака"]
[cols="~,~,~"]
|===
|Оружие| Бросок атаки| Урон
|Короткий лук |+5 |1к6+3
|Двуручный меч |+7 |3к6+5
|Длинный меч |+7 |2к6+5
|===

Любимые приёмы :: Двойной Удар, Мощный Удар (1 SP), и Сплочение (3+ SP)
Сплочение:: Гарлок-вожак может использовать специальный приём Сплочения за 3 SP (или больше).
Действия вожака впечатляют и вдохновляют его войско: все порождения тьмы в радиусе 10 ядов, способные видеть вожака, восстанавливают количество Здоровья, равное Общению вожака плюс число потраченных SP.
Таланты:: Опыт Ношения Брони (Подмастерье), Бой Двуручным Оружием (Подмастерье) и Бой с Оружием и Щитом (Подмастерье).
Типы Оружия :: Мечи, Дробящее, и Тяжёлые клинки
Снаряжение ::
Лёгкие латы, короткий лук, и двуручный меч (или лёгкие латы, длинный меч и большой щит)

[discrete]
== ГЕНЛОК-ВОЖАК ПОРОЖДЕНИЕ ТЬМЫ

Способности (Фокусы)::

* 4 Сила (Топоры, Запугивание)
* 2 Ловкость (Рукопашная)
* 3 Телосложение (Бег)
* 2 Восприятие (Зоркость, Нюх)
* 1 Разум (Знание Военного Дела)
* 2 Воля
* 2 Магия
* 0 Общение (Лидерство)

[caption="Боевые характеристики"]
[cols="~,~,~,~"]
|===
|Скорость |Здоровье |Защита |Класс брони
|6 |55 |11 (13 со щитом)| 7
|===

[caption="Атака"]
[cols="~,~,~"]
|===
|Оружие| Бросок атаки| Урон
|Боевой топор |+6| 2к6+4
|Метательный топор |+6 |1к6+4
|===

Любимые приёмы :: Калечить (3 SP) и Двойной Удар
Калечить :: Генлок-вожак может нанести калечащий удар, потратив на это 3 SP.
Цель атаки получает штраф -2 к броскам атаки и урона, а её скорость уменьшается вдвое.
Штраф -2 снимается через 3 раунда, однако скорость не увеличивается до прежней величины, пока вы не сделаете передышку.
Сопротивление магии:: Генлок-вожак получает бонус +2 к броскам на способности, когда сопротивляется воздействию заклинаний и других магических атак.
Тактический рывок :: Используя приём рывка, генлок-вожак может передвинуть другое порождение тьмы под его командованием на 2 ярда в любом направлении (в дополнение к тому, что этот приём, как обычно, позволяет ему передвинуть себя или противника).
Таланты:: Опыт Ношения Брони (Подмастерье) и Бой с оружием и щитом (Подмастерье).
Типы Оружия :: Топоры, Рукопашная, и Дробящее
Снаряжение ::
Боевой топор, тяжёлая кольчуга, средний щит, и метательный топор.

[discrete]
== ГЕНЛОК-ЭМИССАР ПОРОЖДЕНИЕ ТЬМЫ

Способности (Фокусы)::

* 3 Сила (Тяжёлые Клинки, Запугивание, Посохи)
* 1 Ловкость (Рукопашная)
* 2 Телосложение (Бег)
* 2 Восприятие (Нюх)
* 1 Разум (Знание военного дела)
* 2 Воля
* 4 Магия (Энтропия)
* 1 Общение

[caption="Боевые характеристики"]
[cols="~,~,~,~"]
|===
|Скорость |Здоровье |Защита |Класс брони
|6 |50 |11 |4
|===

[caption="Атака"]
[cols="~,~,~"]
|===
|Оружие| Бросок атаки| Урон
|Длинный меч |+5 |2к6+3
|Посох |+5 |1к6+4
|===

Сила магии:: 18
Мана:: 60
Любимые приёмы :: Сбить с Ног и Мощный Удар.
Сопротивление магии: Генлок получает бонус +2 к броскам на способности, когда сопротивляется воздействию заклинаний и других магических атак.
Заклинания: Вытянуть жизнь, Порча Уязвимости, Слабость, Кровавая жертва, Исцеление, и Молния.
Тактический рывок :: Используя приём рывка, генлок-вожак может передвинуть другое порождение тьмы под его командованием на 2 ярда в любом направлении (в дополнение к тому, что этот приём, как обычно, позволяет ему передвинуть себя или противника).
Таланты:: Опыт Ношения Брони (Подмастерье), Магия Крови (Подмастерье) и Магия Энтропии (Подмастерье).
Типы Оружия :: Тяжёлые клинки, Дробящее, и Посохи .
Снаряжение ::
Длинный меч, посох, тяжёлая кожаная броня.

[discrete]
== ГЕНЛОК-ЭМИССАР ПОРОЖДЕНИЕ ТЬМЫ

Способности (Фокусы)::

* 3 Сила (Тяжёлые Клинки, Запугивание, Посохи)
* 1 Ловкость (Рукопашная)
* 2 Телосложение (Бег)
* 2 Восприятие (Нюх)
* 1 Разум (Знание военного дела)
* 2 Воля
* 4 Магия (Энтропия)
* 1 Общение

[caption="Боевые характеристики"]
[cols="~,~,~,~"]
|===
|Скорость |Здоровье |Защита |Класс брони
|6 |50 |11 |4
|===

[caption="Атака"]
[cols="~,~,~"]
|===
|Оружие| Бросок атаки| Урон
|Длинный меч |+5 |2к6+3
|Посох |+5| 1к6+4
|===

Сила магии:: 18
Мана:: 60
Любимые приёмы :: Сбить с Ног и Мощный Удар.
Сопротивление магии:: Генлок получает бонус +2 к броскам на способности, когда сопротивляется воздействию заклинаний и других магических атак.
Заклинания:: Вытянуть жизнь, Порча Уязвимости, Слабость, Кровавая жертва, Исцеление, и Молния.
Тактический рывок :: Используя приём рывка, генлок-вожак может передвинуть другое порождение тьмы под его командованием на 2 ярда в любом направлении (в дополнение к тому, что этот приём, как обычно, позволяет ему передвинуть себя или противника).
Таланты:: Опыт Ношения Брони (Подмастерье), Магия Крови (Подмастерье) и Магия Энтропии (Подмастерье).
Типы Оружия :: Тяжёлые клинки, Дробящее, и Посохи .
Снаряжение ::
Длинный меч, посох, тяжёлая кожаная броня.

[discrete]
== ГНОМЬИ ПРИЗРАКИ

Способности (Фокусы)::

* 3 Сила (Топоры, Дробящее)
* 2 Ловкость (Рукопашная)
* 4 Телосложение (Выносливость)
* 1 Восприятие
* 0 Разум
* 2 Воля (Мораль)
* 0 Магия
* 0 Общение (Обман)

[caption="Боевые характеристики"]
[cols="~,~,~,~"]
|===
|Скорость |Здоровье |Защита |Класс брони
|12 |25 |11 |0
|===

[caption="Атака"]
[cols="~,~,~"]
|===
|Оружие| Бросок атаки| Урон
|Молот или кирка |+5 |1к6+6
|===

Любимые приёмы :: Сбить с Ног и Рывок
Призраки :: Гномьи призраки-- призрачные существа, невосприимчивые к обычному физическому урона.
Магия и магическое оружие ранит их, как обычно.
Атакующий может также использовать против гномьего призрака специальный приём Атака Призрака за 3 SP, и в этом случает причинит обычный урон, однако должен прибавить к броску урона не Силу (и не Восприятие), а Магию.

[discrete]
== ДУХ ПЕПЛА

Способности (Фокусы)::

* -3 Сила
* 5 Ловкость (Осушающее касание, Пламенная вспышка, Скрытность)
* 0 Телосложение
* 2 Восприятие
* 1 Разум
* 4 Воля
* 5 Магия
* -2 Общение

[caption="Боевые характеристики"]
[cols="~,~,~,~"]
|===
|Скорость |Здоровье |Защита |Класс брони
|15 |35 |15| 0
|===

[caption="Атака"]
[cols="~,~,~"]
|===
|Оружие| Бросок атаки| Урон
|Осушающее касание |+7 |2к6+4 проникающий
|Огненная вспышка |+7 |2к6+4 проникающий
|===

Любимые приёмы :: Молниеносная атака, Внезапная атака, и Вихрь (4 SP).
Бестелесный:: Духи пепла бестелесны, и временно образуют собственные тела из пепла или обломков.
Они игнорируют преграды, а не-магические атаки не причиняют им урона.
Магические (заклинания и волшебное оружие) наносят им обычные повреждения.
Огненная выспышка :: Огненная вспышка действует на ту же область, что и одноимённое заклинание, однако не требует траты маны, причиняет больше урона, и этот урон-- проникающий.
Дух должен сделать отдельный бросок атаки на каждую цель вспышки, и, как и в случае заклинания, цели, атака по которым была удачной, могут сделать бросок на Ловкость (Акробатику) против сложности 15, чтобы уменьшить ущерб до 1к6+2.
Внезапная атака:: Дух пепла может атаковать внезапно, растворившись в воздухе и неожиданно появившись с другой стороны.
Это умение действует так же, как удар в спину разбойника и требует встречного броска на Ловкость (Скрытность) духа против Восприятия (Зоркости) со стороны цели.
Если дух выигрывает, то его следующая атака делается с бонусом +2 и причиняет дополнительные 1к6 урона.
Вихрь :: Дух пепла может использовать Вихрь как специальный приём за 4 SP.
Все противники в радиусе 6 ярдов от духа оказываются захвачены вихрем пепла, который высасывает жизнь, причиняя 1к6+4 проникающего урона каждому

[discrete]
== ЗМЕЙ

Способности (Фокусы)::

* 5 Сила (Когти, Прыжки)
* 5 Ловкость (Огненное Дыхание, Инициатива)
* 5 Телосложение (Бег)
* 4 Восприятие (Зоркость, Выслеживание)
* 0 Разум
* 1 Магия
* 2 Воля (Отвага)
* 0 Общение

[caption="Боевые характеристики"]
[cols="~,~,~,~"]
|===
|Скорость |Здоровье |Защита |Класс брони
|16 |55 |15 |5
|===

[caption="Атака"]
[cols="~,~,~"]
|===
|Оружие| Бросок атаки| Урон
|Укус |+7 |2к6+5
|Когти |+7 |2к6+5
|Огненное дыхание |+7 |3к6
|Удар хвостом |+7 |1к6+5
|===

Любимые приёмы :: Пробить Броню, Разодрать (2 SP) и Удар Хвостом (3 SP).
Огненное дыхание:: Змей может выдыхать пламя в качестве дальнобойной атаки, малая дальность которой равна 6 ярдов, а большая-- 12 ярдов.
За 2 SP змей может выдохнуть пламя, поражая всех в области диаметром 8 ярдов с центром на цели.
Все цели кроме той, на которую изначально была нацелена атака, делают бросок на Ловкость (Акробатику) против Ловкости (Огненное Дыхание) змея, чтобы уменьшить урон вдвое.
Разодрать :: После удачной атаки когтями на передних лапах, змей может нанести удар когтями на задних, -- это считается особым приёмом стоимостью в 2 SP.
Целью второй атаки когтями должен быть тот же противник, на которого была нацелена первая атака.
Если при броске этой атаки на двух и более кубиках выпадут одинаковые числа, змей не получает новых SP.
Удар Хвостом :: Змей может использовать приёмы Мощный Удар и Сбить с Ног одновременно за 3 SP, нанося сильный удар хвостом.
Твёрдая Шкура :: Чешуя змея даёт ему Класс Брони, равный 5

[discrete]
== КРИКУН ПОРОЖДЕНИЕ ТЬМЫ

Способности (Фокусы)::

* 2 Сила
* 5 Ловкость (Инициатива, Лёгкие Клинки, Скрытность)
* 1 Телосложение (Бег)
* 3 Восприятие (Слух, Выслеживание)
* 2 Разум
* 1 Воля
* 2 Магия
* 0 Общение

[caption="Боевые характеристики"]
[cols="~,~,~,~"]
|===
|Скорость |Здоровье |Защита |Класс брони
|16 |35 |15 |3
|===

[caption="Атака"]
[cols="~,~,~"]
|===
|Оружие| Бросок атаки| Урон
|Клинок на руке |+7 |1к6+4
|===

Любимые приёмы :: Молниеносная Атака (2 SP) и Яд (2+ SP).
Бешенство :: Крикуны могут использовать Молниеносную Атаку всего за 2 SP.
Яд:: Успешно атаковав цель и нанеся ей хотя бы единицу урона, крикун может отравить её — этот особый приём стоит 2 SP.
Отравленная жертва должна делать бросок на Телосложение (Выносливость) против сложности 13 в начале своего хода и, в случае провала, получать 1к6+2 проникающего урона.
Действие яда длится столько раундов, сколько SP было потрачено на приём.
Крик :: Визг и вой крикунов, давшие им имя, требуют от них дополнительного действия, и заставляют всех, кто их слышит, сделать бросок на Волю (Отвагу) против сложности 12 или получить штраф -1 к атаке и Защите до конца сцены.
Эффекты Крика не складываются.
Крепкая шкура:: Шкура даёт крикуну Класс Брони, равный 3.
Типы Оружия :: Лёгкие клинки.

[discrete]
== ОГР ПОРОЖДЕНИЕ ТЬМЫ

Способности (Фокусы)::

* 9 Сила (Запугивание, Мощь)
* 1 Ловкость (Метание)
* 8 Телосложение (Выносливость)
* 2 Восприятие (Нюх)
* -1 Разум
* 3 Воля (Отвага, Мораль)
* 1 Магия
* 0 Общение

[caption="Боевые характеристики"]
[cols="~,~,~,~"]
|===
|Скорость |Здоровье |Защита |Класс брони
|12| 80| 11| 7
|===

[caption="Атака"]
[cols="~,~,~"]
|===
|Оружие| Бросок атаки| Урон
|Дубина |+9 |3к6+9
|Удар |+11 |2к6+9
|Бросить Камень |+3| 3к6+9
|===

Любимые приёмы :: Раздавить (3 SP), Смертельный Удар (3 SP), и Топнуть (2 SP).
Раздавить (Crush):: За 3 SP после успешной невооружённой атаки огр может использовать особый приём Раздавить.
Он хватает цель и начинает сдавливать её, причиняя 1к6+9 проникающего урона.
Огр может тратить основное действие в каждом раунде, продолжая сдавливать цель и причинять ей указанный урон, а может дополнительным действием отшвырнуть схваченную цель, причиняя ей 1к6+9 проникающего урона, но освобождая (естественно!) таким образом из хватки.
Чтобы вырваться из хватки самой, цель должна сделать успешный бросок на Силу (Мощь) или Ловкость (Акробатику) против Силы (Мощи) огра.
Соседствующий союзник может также использовать особый приём за 2 SP, чтобы освободить схваченную жертву.
Регенерация: Огр может сделать передышку, потратив на это дополнительное действие и восстанавить этим 5 + Телосложение (обычно 13) очков Здоровья.
Поступь :: Огр может использовать приём Сбить с Ног против всех целей в радиусе 6 ярдов, топнув с огромной силой.
Крепкая Шкура:: Твёрдая, мозолистая шкура даёт ограм класс брони, равный 7.
Снаряжение ::
Огромная Дубина

[discrete]
== Обезумивший отступник (Crazed Apostate)

Способности (Фокусы)::

* 0 Сила
* 0 Ловкость (Посохи)
* 0 Телосложение
* 0 Восприятие
* 2 Разум (Знание Магии)
* 1 Воля
* 3 Магия (Волшебный Жезл, Созидание, Дух)
* 0 Общение

[caption="Боевые характеристики"]
[cols="~,~,~,~"]
|===
|Скорость |Здоровье |Защита |Класс брони
|10
|25
|10
|0
|===

[caption="Атака"]
[cols="~,~,~"]
|===
|Оружие| Бросок атаки| Урон
|Волшебный жезл (Arcane Lance)    |+5            |1к6+2
|Посох (Quarterstaff)            |+2            |1к6+1
|===

Сила Магии:: 13 (15)
Мана:: 24
Заклинания:: Волшебная стрела, Волшебный щит, Исцеление, Героический Натиск, Взрыв Разума.
Любимые приёмы :: Защитная стойка и Рывок.
Последнее средство :: Обезумивший отступник, здоровье которого падает до 10 или ниже, может использовать заклинание кровоточащая рана, получая +1 к Магии, и фокус Магии (Кровь).
Это преимущество сохраняется, пока маг не умрёт, даже если его Здоровье поднимается выше 10.
Оружие:: Рукопашная и Посохи.
Снаряжнение::
Посох.

[discrete]
== Маг Крови (Blood Mage)

Способности (Фокусы)::

* 0 Сила
* 0 Ловкость (Посохи)
* 3 Телосложение (Выносливость)
* 0 Восприятие
* 2 Разум (Знание Магии)
* 1 Воля
* 5 Магия (Волшебный Жезл, Кровь, Дух)
* 0 Общение

[caption="Боевые характеристики"]
[cols="~,~,~,~"]
|===
|Скорость |Здоровье |Защита |Класс брони
|10|40|10|0
|===

[caption="Атака"]
[cols="~,~,~"]
|===
|Оружие| Бросок атаки| Урон
|Волшебный жезл (Arcane Lance)    |+7            |1к6+5
|Посох (Quarterstaff)            |+2            |1к6+1
|===

Сила Магии:: 15 (17)
Мана:: 47
Заклинания:: Волшебная стрела, Кровавая Жертва, Кровоточащая Рана, Волшебный Щит, и Дыба.
Любимые приёмы :: Рывок и Насмешка.
Магия Крови :: Творя заклинание, маг крови может черпать силы из крови существа в радиусе 6 ярдов (включая себя самого).
Использование крови цели против её воли требует броска на Магию (Кровь) против Воли (Вера или Самоконтроль).
Цель получает 1к6 проникающего урона (или 2к6 проникающего урона, если цель находится по соседству и беспомощна), и маг крови получает число очков маны, равное нанесённому урону.
Эти очки маны должны использоваться на заклинание, которое маг накладывает в данный момент.
Щит крови :: Когда на маге крови наложен волшебный щит, и враг атакует его, он получает 1к6 проникающего урона, а маг крови восстанавливает количества Здоровья, равное полученному урону.
Оружие:: Рукопашное и Посохи.
Снаряжение ::
Посох и кинжал.

[discrete]
== БАНДИТЫ (BRIGANDS)

Неохраняемые дороги и тёмные углы по всему Тедасу кишат грабителями и головорезами всех мастей.
Начиная от Орзаммара с его Хартией и заканчивая Киркволлом с его бесчисленными бандами работорговцев и воров, эти беспринципные личности заставляют честных людей держать ухо востро.
Хотя многие из них стали бандитами от отчаяния, почти всем им нравится жизнь, которую они ведут, полная насилия и грабежей.
Приведённые ниже характеристики отражают способности среднестатистической банды головорезов, разбойников, или воров.
Банды сильно различаются между собой, поэтому слегка измените снаряжение и характеристики, чтобы отразить это разнообразие.
В таблице Типы баднитов и оружие вы найдёте советы, какие фокусы и оружие добавлять для разных типов бандитов.

[discrete]
== Бандит-головорез (Brigand Thug)

Способности (Фокусы)::

* 3 Сила (Дробящее, Запугивание)
* 1 Ловкость (Рукопашная, Лёгкие Клинки)
* 2 Телосложение
* 0 Восприятие
* 0 Разум
* -1 Воля
* 0 Магия
* -1 Общение

[caption="Боевые характеристики"]
[cols="~,~,~,~"]
|===
|Скорость |Здоровье |Защита |Класс брони
|10|15|11|4
|===

[caption="Атака"]
[cols="~,~,~"]
|===
|Оружие| Бросок атаки| Урон
|Молот        |+5            |1к6+6
|Метательный нож        |+3            |1к6+3
|===

Любимые приёмы :: Могучий Удар и Угроза.
Мы-- банда :: Бандиты-головорезы получают бонус к урона, равный количеству их союзников, соседствующих с целью (максимум два) и бонус +2 к броскам на Волю (Мораль), если бандитов больше, чем врагов.
Типы Оружия :: Дробящее, Рукопашная, Лёгкие Клинки, и Посохи.
Снаряжение ::
Молот, метательный нож, легкий щит, и тяжёлая кольчуга.

[discrete]
== Бандит-стрелок

Способности (Фокусы)::

* 1 Сила
* 3 Ловкость (Луки, Лёгкие Клинки)
* -1 Телосложение
* 2 Восприятие (Зоркость)
* 0 Разум
* 0 Воля
* 0 Магия
* -1 Общение

[caption="Боевые характеристики"]
[cols="~,~,~,~"]
|===
|Скорость |Здоровье |Защита |Класс брони
|13|12|13|3
|===

[caption="Атака"]
[cols="~,~,~"]
|===
|Оружие| Бросок атаки| Урон
|Арбалет        |+5            |2к6+3
|Кинжал        |+5            |1к6+2
|===

Любимые приёмы :: Пробить Броню, Быстрая Перезарядка, и Рывок.
Мы-- банда :: Бандиты-стрелки получают бонус к урона, равный количеству их союзников, соседствующих с целью (максимум два) и бонус +2 к броскам на Волю (Мораль), если бандитов больше, чем врагов.
Типы Оружия :: Луки, Рукопашная, и Лёгкие Клинки.
Снаряжение ::
Арбалет, кинжал, и лёгкая кожаная броня.

[discrete]
== Главарь бандитов (Brigand Lieutenant)

Способности (Фокусы)::

* 3 Сила (Тяжёлые клинки, Запугивание)
* 2 Ловкость (Лёгкие Клинки)
* 2 Телосложение
* 0 Восприятие
* 1 Разум
* 1 Воля (Мораль)
* 0 Магия
* 2 Общение (Лидерство)

[caption="Боевые характеристики"]
[cols="~,~,~,~"]
|===
|Скорость |Здоровье |Защита |Класс брони
|10|28|12|5
|===

[caption="Атака"]
[cols="~,~,~"]
|===
|Оружие| Бросок атаки| Урон
|Длинный меч    |+5            |2к6+3
|Кинжал        |+4            |1к6+3
|===

Любимые приёмы :: Наступление (2 ОП), Обезоруживание, Перехват Инициативы, и Насмешка.
Боевой лидер :: Союзники в радиусе 2 ярдов вокруг главаря бандитов получают бонус +1 к броскам на Волю и бонус +1 к ОП, когда выпадают дубли.
В один момент времени союзник может получать бонусы только от одного лидера в бою.
Наступление :: Главарь бандитов может изменить позицию своих союзников, использовав особый приём за 2 ОП. Союзники, число которых не превышает Общения главаря, находящие в радиусе 12 ярдов от него, могут передвинуться на 2 ярда в любом направлении.
Мы-- банда:: Главарь бандитов получает бонус к урону, равный количеству их союзников, соседствующих с целью (максимум два) и бонус +2 к броскам на Общение (Лидерство) и на Волю (Мораль), если бандитов больше, чем врагов.
Типы Оружия :: Рукопашная, Тяжёлые Клинки и Лёгкие Клинки.
Снаряжение ::
Длинный меч, метательный нож, средний щит, и лёгкая кольчуга.

[caption="Типы бандитов и оружие"]
[cols="~,~,~,~"]
|===
|Тип            |Фокус                    |Головорез        |Стрелок
|Хартия        |Телосложение (Выносливость)    |Боевой топор        |Арбалет
|Горец            |Ловкость (Верховая езда)        |Длинный меч        К|ороткий лук
|Пират            |Телосложение (Плавание)        |Короткий меч    |Арбалет
|Городской бандит    |Ловкость (Скрытность)        |Короткий меч    |Арбалет
|===

[discrete]
== Демон Гнева (Rage Demon)

Способности (Фокусы)::

* 4 Сила (Когти)
* 4 Ловкость (Инициатива, Скрытность)
* 1 Телосложение
* 1 Восприятие
* -1 Разум
* 0 Воля
* 3 Магия
* -2 Общение

[caption="Боевые характеристики"]
[cols="~,~,~,~"]
|===
|Скорость |Здоровье |Защита |Класс брони
|14|50|14|4
|===

[caption="Атака"]
[cols="~,~,~"]
|===
|Оружие| Бросок атаки| Урон
|Когти    |+5            |2к6+4
|===

Любимые приёмы :: Пробить броню, Поджечь (2 ОП), и Рывок.
Огненная аура :: Демоны ярости окружены огненной аурой.
Любое существо, соседствующее с демоном, поучает 2 проникающего урона в начале каждого хода демона.
Шкура демона:: Тело демона, напоминающее расплавленный металл, даёт ему Класс Брони, равный 4.
Сопротивление Огню :: Демон гнева не получает урона от атак огнём (например, если вы используете огненную вспышку или огненный шар).
Непоколебимый:: На демона ярости не действуют приёмы рывок и сбить с ног.
Поджечь :: Демон ярости может поджечь цель, использовав специальный приём за 1 ОП. Цель получает 1к6 проникающего урона в начале каждого раунда, пока не потратит дополнительное действие на то, чтобы затушить пламя.

[discrete]
== Демон Праздности (Sloth Demon)

Способности (Фокусы)::

* 2 Сила (Когти)
* -2 Ловкость
* 1 Телосложение
* 1 Восприятие (Эмпатия)
* 1 Разум
* 0 Воля
* 4 Магия (Энтропия, Элементы)
* 3 Общение (Обман, Убеждение)

[caption="Боевые характеристики"]
[cols="~,~,~,~"]
|===
|Скорость |Здоровье |Защита |Класс брони
|8|60|8|6
|===

[caption="Атака"]
[cols="~,~,~"]
|===
|Оружие| Бросок атаки| Урон
|Когти |    +4            |2к6+2
|===

Сила Магии:: 14 (16)
Мана:: 45
Заклинания:: Высосать жизнь, Исцеление, Паралич и Слабость.
Любимые приёмы :: Двойной удар и Быстрое колдовство (3 ОП).
Шкура демона:: Странная плоть демона праздности даёт ему класс брони, равный 6.
Непоколебимый:: На демона праздности не действуют приёмы рывок и сбить с ног.
Могучее высасывание жизни :: Когда демон праздности использует заклинание высасывания жизни, оно действует на всех, кто в этот момент парализован его заклинанием.

[discrete]
== Демон Желания (Desire Demon)

Способности (Фокусы)::

* 1 Сила
* 3 Ловкость (Рукопашная)
* 0 Телосложение
* 3 Восприятие (Эмпатия)
* 3 Разум
* 2 Воля
* 5 Магия (Волшебный Жезл, Энтропия)
* 4 Общение (Обман, Убеждение, Соблазнение)

[caption="Боевые характеристики"]
[cols="~,~,~,~"]
|===
|Скорость |Здоровье |Защита |Класс брони
|13|50|13|7
|===

[caption="Атака"]
[cols="~,~,~"]
|===
|Оружие| Бросок атаки| Урон
|Волшебный жезл        |+7            |1к6+5
|Кулак                |+5            |1к3+1
|===

Сила магии:: 15 (17)
Мана:: 55
Заклинания:: Болезненная Порча, Раб крови, Ошеломление, Высосать жизнь, Паралич, и Порча Уязвимости
Любимый приём:: Вопль (3 ОП) и Насмешка.
Аура сопротивления магии :: Демон желания и все его союзники, находящие не далее 6 ярдов от него, получают бонус +1 к броскам сопротивления заклинаниям и другим магическим эффектам.
Бонус поднимается до +2 в случае заклинаний Духа и эффектов, схожих с ней.
Шкура Демона:: Магическая аура демона желания даёт ему Класс Брони, равный 4.
Непоколебимый:: На демона желания не действуют приёмы рывок и сбить с ног.
Вопль :: Использовав приём за 3 ОП, демон желания может издать пронзительный вопль.
Все персонажи в радиусе 10 ярдов от демона получают 1к6 проникающего урона и должны сделать успешный бросок на Магию (Дух) против сложности 15 или в свой следующий ход потерять основное действие.

[discrete]
== Демон Гордыни (Pride Demon)

Способности (Фокусы)::

* 4 Сила (Когти)
* 3 Ловкость
* 1 Телосложение (Выносливость)
* 0 Восприятие
* 2 Разум
* 2 Воля
* 6 Магия (Элементы)
* 2 Общение (Обман, Убеждение)

[caption="Боевые характеристики"]
[cols="~,~,~,~"]
|===
|Скорость |Здоровье |Защита |Класс брони
|13|85|13|10
|===

[caption="Атака"]
[cols="~,~,~"]
|===
|Оружие| Бросок атаки| Урон
|Когти    |+7            |2к6+5
|===

Любимые приёмы :: Сбить с ног, Волна Маны (4 ОП) и Мощный удар
Шкура демона:: Твёрдая, как камень, шкура демона гордыни даёт ему Класс Брони, равный 7.
Непоколебимый:: На демона гордыни не действуют приёмы рывок и сбить с ног.
Волна маны :: Когда демон гордыни использует особый приём за 4 ОП, вокруг него расходится волна маны.
Все магические эффекты в радиусе 6 ярдов повергаются действию заклинания развеивание магии (так, как будто демон сотворил его).
Маги в области поражения также теряют 1к6 маны.
Элементальный взрыв :: Эта способность требует от демона использования малого действия, и при её применении вокруг демона гордыни расходятся волны огненной или ледяной энергии (на его выбор).
Все в радиусе 2 ярдов от демона получают урон (2к6+3 огненного урона или 1к6+2 проникающего урона льдом), однако успешный бросок на Ловкость (Акробатику) против сложности 18 снижает полученный урон вдвое.

[discrete]
== Одержимый (Abomination)

* 0 Сила
* 2 Ловкость (Рукопашная)
* 2 Телосложение (Выносливость)
* 0 Восприятие
* 0 Разум
* 1 Воля
* 4 Магия (Когти)
* -1 Общение

[caption="Боевые характеристики"]
[cols="~,~,~,~"]
|===
|Скорость |Здоровье |Защита |Класс брони
|11|40|12|4
|===

[caption="Атака"]
[cols="~,~,~"]
|===
|Оружие| Бросок атаки| Урон
|Когти    |+6            |2к6+4
|===

Любимые приёмы :: Молниеносный удар демона (3 ОП) и Могучий удар.
Молниеносный удар демона :: Одержимый может использовать особый приём— молниеносный удар демона— за 3 ОП. По сути он ничем не отличается от приёма молниеносной атаки, однако вдобавок к полученному урону цель начинает страдать от воздействия определённого заклинания.
Броска на заклинание одержимый не делает, а его Сила Магии, которая учитывается при броске сопротивления, равна 15. Выберите одно из следующих заклинаний в зависимости от типа одержимого: ошеломление (одержимый желанием или гневом), высосать жизнь (голодом или гордыней), или слабость (желанием или праздностью).
Цель заклинания— та же, что и цель атаки.
Взрывающаяся плоть :: Когда Здоровье одержимого опускается до 0, то он взрывается.
Все в радиусе 2 ярдов от одержимого получают 2к6 урона.
Магическая мощь :: Бонус к броскам атакам и урона одержимого в ближнем бою равен его Магии.
Также фокус Когтей являются для него фокусом Магии.
Толстая шкура :: Толстая, искорёженная плоть одержимого даёт ему Класс Брони, равный 4.

[discrete]
== Каменный голем (Stone Golem)

Способности (Фокусы)::

* 6 Сила (Каменный кулак)
* -1 Ловкость
* 7 Телосложение (Выносливость)
* 2 Восприятие
* 0 Разум
* 3 Воля (Отвага)
* 2 Магия
* 0 Общение

[caption="Боевые характеристики"]
[cols="~,~,~,~"]
|===
|Скорость |Здоровье |Защита |Класс брони
|9|80|9|10
|===

[caption="Атака"]
[cols="~,~,~"]
|===
|Оружие| Бросок атаки| Урон
|Каменный кулак|    +8            |2к6+6
|Бросить камень |+6            |1к6+8
|===

Любимые приёмы :: Волшебные кулаки (1 ОП), Двойной Удар и Сотрясение (2 ОП).
Волшебные кулаки :: Каменный голем может зарядить свои кулаки магической энергией, использовав специальный приём за 1 ОП. Цель получает дополнительные 1к6 проникающего урона.
Сотрясение :: Каменный голем может сбить с ног все цели в радиусе 4 ярдов, использовав этот особый приём за 2 ОП.
Каменное тело:: Благодаря телу, состоящему из камня, голем получает класс брони, равный 10.
Бросок камня:: Голем может совершать дальнобойную атаку, бросая огромные валуны.
Максимальная дальность броска равна 12 ярдам.

[discrete]
== Стальной Голем (Steel Golem)

Способности (Фокусы)::

* 8 Сила (Стальной кулак)
* 0 Ловкость
* 8 Телосложение (Выносливость)
* 2 Восприятие
* 0 Разум
* 4 Воля (Отвага)
* 2 Магия
* 0 Общение

[caption="Боевые характеристики"]
[cols="~,~,~,~"]
|===
|Скорость |Здоровье |Защита |Класс брони
|10|90|10|10
|===

[caption="Атака"]
[cols="~,~,~"]
|===
|Оружие| Бросок атаки| Урон
|Стальной кулак        |+10            |2к6+8
|Брошенный камень        |+8            |1к6+10
|===

Любимые приёмы :: Волшебные кулаки (1 ОП), Двойной удар, и Сотрясение (2 ОП).
Волшебные кулаки :: Стальной голем может зарядить свои кулаки магической энергией, использовав специальный приём за 1 ОП. Цель получает дополнительные 1к6 проникающего урона.
Взрыв электричества :: Стальной голем может, использовав особый приём за 2 ОП, окатить всех вокруг волной электрических разрядов.
Противники в радиусе 6 ярдов вокруг него получают 1к6+4 проникающего урона.
В случае успешного броска на Телосложение (Выносливость) против сложности 14 цель получает только 1к6 проникающего урона.
Взрыв электричества создаёт магнитное поле, притягивающее цели в латах и кольчуге на 4 ярда ближе к голему.
Сотрясение :: Стальной голем может сбить с ног все цели в радиусе 4 ярдов, использовав этот особый приём за 2 ОП.
Стальное тело:: Благодаря стальному телу, голем получает класс брони, равный 10.
Бросок камня:: Голем может совершать дальнобойную атаку, бросая огромные валуны.
Максимальная дальность броска равна 12 ярдам.

[discrete]
== Высший дракон (High Dragon)

Способности (Фокусы)::

* 9 Сила (Когти)
* 5 Ловкость (Укус, Пламя)
* 8 Телосложение (Выносливость)
* 4 Восприятие (Слух, Зрение)
* -1 Разум
* 6 Воля (Отвага, Мораль)
* 3 Магия
* -1 Общение

[caption="Боевые характеристики"]
[cols="~,~,~,~"]
|===
|Скорость |Здоровье |Защита |Класс брони
|14 (полёт 15)|200|15|11
|===

[caption="Атака"]
[cols="~,~,~"]
|===
|Оружие| Бросок атаки| Урон
|Укус                |+7            |2к6+9
|Когти                |+11        |    2к6+9
|Сгусток пламени    |    +7        |    3к6+4
|Удар хвостом        |    +5        |    1к6+9
|===

Любимые приёмы :: Смертельный удар (5 ОП), Молниеносная атака (3 ОП), Пробивание брони (2 ОП), и Удар хвостом (2 ОП).
Удар крыльями :: Использовав дополнительное действие, высший дракон может взмахнуть крыльями, сбив с ног стоящих поблизости существ.
Все в радиусе 4 ярдов от дракона должны сделать бросок на Силу (Мощь) против сложности 15 или быть отброшенными на 1к6 ярдов.
Тот, кто провалил бросок и у кого на Кубике Дракона выпало 1 или 2, сбит с ног.
Огненное дыхание:: Высший дракон может, использовав основное действие, выдыхать пламя как широким потоком (4 ярда в длину и 6 ярдов в ширину), так и тонкой струёй (8 ярдов в длину и 2 ярда в ширину).
Те, кто оказался в зоне поражения, получают 2к6 проникающего урона.
Успешный бросок на Ловкость (Акробатику) против сложности 18 снижает урон до 1к6 проникающего.
Пламя :: Высший дракон может в качестве дальнобойной атаки выплюнуть сгусток пламени.
Малая дальность сгустка пламени равна 12 ярдам, высокая— 24 ярдам.
Громадная тварь :: Немногие животные могут сравниться по величине и силе с высшим драконом.
На него не действуют приёмы рывок и сбить с ног.
Также все противники в радиусе 4 ярдов вокруг высшего дракона считаются соседствующими с ним.
Рёв :: Оглушительный рык высшего дракона заставляет кровь стынуть в жилах.
Он может использовать основное действие, чтобы взреветь; все противники в радиусе 24 ярдов должны сделать бросок на Волю (Отвагу) против сложности 15. Те, кто провалил бросок, в следующем раунде могут использовать основное действие только на бег, и ни на что другое.
Удар хвостом :: Использовав особый приём за 2 ОП, высший дракон может ударить хвостом любого противника, с которым соседствует.
Дракон не получает ОП за дубли, выпавшие на броске этой атаки.
Клык и коготь :: Высший дракон— опасный противник.
За одно основное действие он может атаковать зубами и когтями одновременно.
Он получает ОП от обоих атак.
Толстая шкура:: Толщина драконьей шкуры вошла в легенды.
Его Класс Брони равен 11.

[discrete]
== Храмовник (Templar)

Способности (Фокусы)::

* 3 Сила (Топоры, Тяжёлый Клинки)
* 0 Ловкость
* 2 Телосложение
* 0 Восприятие
* 0 Разум (Знание религии)
* 2 Воля (Вера)
* 3 Магия
* 0 Общение (Расследование)

[caption="Боевые характеристики"]
[cols="~,~,~,~"]
|===
|Скорость |Здоровье |Защита |Класс брони
|6|25|12|8
|===

[caption="Атака"]
[cols="~,~,~"]
|===
|Оружие| Бросок атаки| Урон
|Длинный меч            |+5            |2к6+3
|Метательный топор        |+5            |1к6+5
|===

Любимые приёмы :: Рассеивающий удар (2 ОП) и Обезоруживание.
Рассеивающий удар :: Храмовник может рассеять магию, использовав особый приём, который стоит 2 ОП. Все действующие на цель заклинания, равно как и те, которые цель в данный момент колдует, рассеиваются немедленно.
Убийца магов :: Когда храмовник наносит магу или другому существу, у которого есть мана, урон, цель теряет 1к6+3 MP.
Эссенция лириума :: Храмовники получают бонус +1 на броски сопротивления заклинаниям и другим магическим эффектам.
Типы Оружия :: Топоры, Дубины, Рукопашная, Тяжёлые клинки, и Копья.
Снаряжение ::
Длинный меч, метательный топор, маленький щит и лёгкие латы.

[discrete]
== Рыцарь-командор (Knight-Captain)

Способности (Фокусы)::

* 5 Сила (Тяжёлые Клинки)
* 0 Ловкость (Луки, Инициатива)
* 2 Телосложение
* 2 Восприятие
* 1 Разум (Знание религии)
* 3 Воля (Отвага, Вера)
* 4 Магия
* 3 Общение (Расследование, Лидерство, Убеждение)

[caption="Боевые характеристики"]
[cols="~,~,~,~"]
|===
|Скорость |Здоровье |Защита |Класс брони
|5|50|12|10
|===

[caption="Атака"]
[cols="~,~,~"]
|===
|Оружие| Бросок атаки| Урон
|Полуторный меч        |+7            |2к6+5
|Арбалет            |+7            |1к6+7
|===

Любимые приёмы :: Обезоруживание, Праведное Рвение (2 ОП)
Праведное рвение :: Рыцарь-командор может наполнить себя и своих союзников праведным рвением, использовав особый приём за 2 ОП. Рыцарь-командор и его союзники в радиусе 6 ярдов от него получают бонус +1 к броскам атаки и бонус +2 к скорости на следующих ход.
Убийца магов :: Когда рыцарь-командор наносит магу или другому существу, у которого есть мана, урон, цель теряет 1к6+4 MP.
Очищение :: Рыцарь-командор может очистить окружающую область от действующей магии.
Это требует от него основного действия, и он получает штраф -2 к атаке до начала своего следующего хода.
Все действующие заклинания и заклинания, которые творят в радиусе 6 ярдов вокруг храмовника, немедленно рассеиваются.
Эссенция лириума :: Рыцарь-командор получает бонус +2 на броски сопротивления заклинаниям и другим магическим эффектам.
Храмовники в радиусе 6 ярдов от рыцаря-командора могут поднять свой бонус эссенции лириума на 1. Существо может получать выгоду только от одной эссенции лириума.
Типы Оружия :: Топоры, Дубины, Рукопашная, Тяжёлые клинки, и Копья.
Снаряжение ::
Меч-бастард, арбалет, средний щит и тяжёлые латы.


