=== ОТСТУПНИК

Если вы решили играть за отступника, то внесите следующие изменения:

• Добавьте 1 к вашей Воле.
Отступнику нужен сильный дух, чтобы противостоять демонам.
• Выберите один из следующих фокусов: Разум (Знание Природы) и Воля (Самоконтроль).
• Выберите расу персонажа: человек или эльф.
• Вы можете говорить и читать на торговом языке.
• Возьмите класс мага.

Сделайте два броска по приведённой ниже таблице и обратитесь к колонке, соответствующей расе вашего героя (человек или эльф) чтобы узнать, какие преимущества вы получили.
Если результаты обоих бросков одинаковы, то перебрасывайте кубики до тех пор, пока не выпадет иное число.

[caption="Таблица 2. "]
.ОТСТУПНИК
|===
|Бросок 2к6| Преимущества эльфа| Преимущества человека
|2
|+1 Разум
|+1 Телосложение
|3 – 4
|Эльфийский язык
|Фокус: Телосложение (Выносливость)
|5
|Фокус: Разум (Знание культуры)
|Фокус: Воля (Самоконтроль)
|6
|Фокус: Воля (самоконтроль)
|Фокус: Разум (Лечение)
|7 – 8
|+1 Магия
|+1 Магия
|9
|Фокус: Ловкость (Скрытность)
|Фокус: Ловкость (Бег)
|10 – 11
|+1 Ловкость
|Фокус: Общение (Обман)
|12
|Тип оружия: Луки +1
|Разум
|===
